### ISSUE TITLE
send button gets stuck with utf8 in title

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1048]

**Comment by tomholub** [comment]
```
Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
at str_base64url_encode (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:389:12)
at Object.str_html_attribute_encode [as html_attribute_encode] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:378:12)
at tool.api.cryptup.message_token.validate.then.response (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:668:91)
```
