### ISSUE TITLE
flowcrypt not set up yet error - when not set up yet

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1140]
```
settings.js:286 Uncaught (in promise) UnreportableError: Cannot find primary key. Is FlowCrypt not set up yet?
    at abort_and_render_error_if_keyinfo_empty (chrome-extension://gggocmadhdlnkbcmbmjfgogjdhkacdgd/chrome/settings/settings.js:286:9)
    at tool.catch.try (chrome-extension://gggocmadhdlnkbcmbmjfgogjdhkacdgd/chrome/settings/modules/security.js:7:2)
UnreportableError @ common.js:6
abort_and_render_error_if_keyinfo_empty @ settings.js:286
tool.catch.try @ security.js:7
async function (async)
tool.catch.try @ security.js:3
(anonymous) @ common.js:3473
(anonymous) @ security.js:86
```
this is on gmail connect screen in settings

**Comment by tomholub** [comment]
I think we removed the security box recently

**Comment by tomholub** [comment]
Which should have resolved this. Security settings are still accessible through the `Security` tile.
