### ISSUE TITLE
user-display common errors instead of reporting them

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1163]

**Comment by tomholub** [comment]
```
at Object.new_network_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1615:128)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:2842:31
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at Object.error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:2847:9)
at u (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27457)
at Object.fireWith [as rejectWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:28202)
at k (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:77676)
at Object.abort (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:75386)


No internet connection, please try again
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/_generated_background_page.html
```

**Comment by tomholub** [comment]
```
rror: unhandled_promise_reject_object with stack
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at handle_promise_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3324:17)


details: {"status":null,"internal":"network","message":"No internet connection, please try again"}

at Object.new_network_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1615:128)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:2842:31
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at Object.error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:2847:9)
at u (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27457)
at Object.fireWith [as rejectWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:28202)
at k (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:77676)
at XMLHttpRequest.<anonymous> (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:79882)

Error
unhandled_promise_reject_object with stack
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/_generated_background_page.html
```

**Comment by tomholub** [comment]
x11
```
Error: unhandled_promise_reject_object with stack
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at handle_promise_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3324:17)


details: {"log":true}

Error: Cannot render page (expected account_email to be of type string but got undefined)<br><br>Was the URL editted manually? Please write human@flowcrypt.com for help.
at Object.abort_and_render_error_on_url_param_mismatch (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1282:11)
at Object.string (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:282:38)
at tool.catch.try (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/help.js:5:49)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/help.js:31:3

Error
unhandled_promise_reject_object with stack
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/help.htm?placement=setti
```

**Comment by tomholub** [comment]
x11
```
{"readyState":4,"responseText":"{\n \"error\": \"invalid_grant\",\n \"error_description\": \"Token has been expired or revoked.\"\n}\n","responseJSON":{"error":"invalid_grant","error_description":"Token has been expired or revoked."},"status":400,"statusText":"error"}

thrown_object
thrown_object
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.htm?placement=set
```
