### ISSUE TITLE
settings is not defined

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1164]
```
Error: unhandled_promise_reject_object with stack
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at handle_promise_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3324:17)


details: {}

ReferenceError: Settings is not defined
at tool.catch.try (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attest.js:9:2)
```

**Comment by tomholub** [comment]
```
Error
unhandled_promise_reject_object with stack
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attest.htm?attest_packet=-----BE
```
