### ISSUE TITLE
compose: token expired error should renew (or show to user only?)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1165]
```
Error: Error/Exception | failed to send message
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at Composer.handle_send_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:1326:16)
at Composer.extract_process_send_message (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:451:10)


details: {"readyState":4,"responseText":"{\n \"error\": \"invalid_grant\",\n \"error_description\": \"Token has been expired or revoked.\"\n}\n","responseJSON":{"error":"invalid_grant","error_description":"Token has been expired or revoked."},"status":400,"statusText":"error"}


Error
Error/Exception | failed to send message
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?is_reply_box=___cu_f
```

**Comment by tomholub** [comment]
closed in close #1166 - hopefully
