### ISSUE TITLE
auth popup needed notifications in settings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1166]
```
Error: tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1546:22
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1555:8
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at messageListener (extensions::messaging:240:29)


details: Message sender stack:
at Object.send (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1484:144)
at Object.notify_parent_if_auth_popup_needed (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1654:27)
at p.catch.e (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:253:31)

Error
tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/index.htm?account_email=cassandr
```

**Comment by tomholub** [comment]
```
Error: tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1546:22
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1555:8
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at messageListener (extensions::messaging:240:29)


details: Message sender stack:
at Object.send (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1484:144)
at Object.notify_parent_if_auth_popup_needed (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1654:27)
at p.catch.e (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:253:31)

Error
tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/index.htm?account_email=dennyasd
```

**Comment by tomholub** [comment]
x6
```
Error: tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1546:22
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1555:8
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at messageListener (extensions::messaging:240:29)


details: Message sender stack:
at Object.send (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1484:144)
at Object.notify_parent_if_auth_popup_needed (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1654:27)
at p.catch.e (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:253:31)

Error
tool.browser.message.listen error: handler "notification_show_auth_popup_needed" not set
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/index.htm?account_email=ss1shris
```
