### ISSUE TITLE
handler google_auth_window_result not set

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1167]
x6
```
Error: tool.browser.message.listen error: handler "google_auth_window_result" not set
at Object.report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3186:11)
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1546:22
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3244:14
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1555:8
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at messageListener (extensions::messaging:240:29)


details: Message sender stack:
at Object.send (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1484:144)
at setInterval (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/content_scripts/oauth_window/google.js:18:24)

Error
tool.browser.message.listen error: handler "google_auth_window_result" not set
url: https://mail.google.com/mail/u/0/#inbox
```

**Comment by tomholub** [comment]
Not sure how to investigate this

**Comment by tomholub** [comment]
this should be fixed now
