### ISSUE TITLE
deal with deleted google account - error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1244]
```
I keep getting this every time I either reply or send "secure email".


--------- BUG REPORT ----------

[name]
composer: send: bad request

[stack]
    at Function.Extension.prepare_bug_report (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:129:21)
    at Composer.handle_send_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:1417:51)
    at Composer.extract_process_send_message (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:507:10)

[error]
{
  "readyState": 4,
  "responseText": "{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Account has been deleted\"\n}",
  "responseJSON": {
    "error": "invalid_grant",
    "error_description": "Account has been deleted"
  },
  "status": 400,
  "statusText": "error"
}

[details]
{}
```

> Yes, her email was deleted and then created again.  Should she uninstall and reinstall the program on her computer?

It should work after going through auth, so we could treat this as an "needs_auth_popup" - easy enough fix.

**Comment by tomholub** [comment]
wontfix
