### ISSUE TITLE
OpenPGP.js upgrade to v4

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1281]

**Comment by tomholub** [comment]
related https://github.com/FlowCrypt/flowcrypt-browser/issues/1175

**Comment by tomholub** [comment]
uuid errs empty

**Comment by tomholub** [comment]
```
typeof:object:[object Object]] {\"registered\":false,\"error\":{\"message\":\"Wrong uuid format\",\"code\":400,\"internal\":\"uuid\"},\"verified\":false,\"subscription\":null}
    at async <anonymous> (/home/runner/flowcrypt-browser/extension/js/common/api/api.ts:701:12)
    at async <anonymous> (/home/runner/flowcrypt-browser/extension/js/common/api/api.ts:460:17)
    at async register? (/home/runner/flowcrypt-browser/extension/js/common/account.ts:62:12)
    at async subscribe? (/home/runner/flowcrypt-browser/extension/js/common/account.ts:47:13)", 
    
```
