### ISSUE TITLE
data.public_keys is not iterable error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1335]
```
ypeError: data.public_keys is not iterable
at Object.render_public_keys (chrome-extension://gggocmadhdlnkbcmbmjfgogjdhkacdgd/js/content_scripts/webmail_bundle.js:8135:48)
at chrome.runtime.onMessage.addListener (chrome-extension://gggocmadhdlnkbcmbmjfgogjdhkacdgd/js/content_scripts/webmail_bundle.js:3062:79)
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at messageListener (extensions::messaging:240:29)
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
```

**Comment by tomholub** [comment]
old version
