### ISSUE TITLE
google api error: extension blocked by admin policy

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1409]
```
[name]
composer: send: bad request

[stack]
    at Function.Extension.prepareBugReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/extension.js:14:16)
    at Composer.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:1441:50)
    at Composer.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:525:10)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?......................


[error]
{
  "xhr": {
    "readyState": 4,
    "responseText": "{\n  \"error\": \"admin_policy_enforced\",\n  \"error_description\": \"This application is currently blocked.\\nIf you require access, please visit ........................ and submit a \\u0026amp;#39;Chrome and G-Suite Extension Review\\u0026amp;#39; request. The form can be found at this link: .........................................\n}",
    "responseJSON": {
      "error": "admin_policy_enforced",
      "error_description": "This application is currently blocked.\nIf you require access, please visit ........................ and submit a &amp;#39;Chrome and G-Suite Extension Review&amp;#39; request. The form can be found at this link: ........................"
    },
    "status": 400,
    "statusText": "Bad Request"
  },
  "status": 400,
  "url": "...",
  "responseText": "{\n  \"error\": \"admin_policy_enforced\",\n  \"error_description\": \"This application is currently blocked.\\nIf you require access, please visit ......... and submit a \\u0026amp;#39;Chrome and G-Suite Extension Review\\u0026amp;#39; request. The form can be found at this link: ...\"}",
  "statusText": "Bad Request"
}

[details]
{}



FlowCrypt chrome 6.3.5
```

**Comment by tomholub** [comment]
One more:
```
{
"error": "admin_policy_enforced",
"error_description": "Access to your account data is restricted by policies within your organization. Please contact administrator for more information."
}
```

**Comment by tomholub** [comment]
in compose:
```
at <async> ajax (/extension/js/common/api/api.ts:670:23)
at <async> googleApiAuthHeader (/extension/js/common/api/google.ts:510:38)
at <async> gmailCall (/extension/js/common/api/google.ts:43:28)
at <async> fetchMsgsHeadersBasedOnQuery (/extension/js/common/api/google.ts:371:34)
at <async> apiGmailLoopThroughEmailsToCompileContacts (/extension/js/common/api/google.ts:442:62)
at <async> searchContacts (/extension/js/common/api/google.ts:298:20)
```

**Comment by tomholub** [comment]
And when sending:
```
at Function.Extension.prepareBugReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/extension.js:15:16)
    at Composer.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:1479:51)
    at Composer.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:540:11)

```

**Comment by tomholub** [comment]
one more when rendering inbox
