### ISSUE TITLE
handle no pubkey in storage when saving draft

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1460]

**Comment by tomholub** [comment]
```
Error: FlowCrypt is not properly set up. No Public Key found in storage.
at Object.storageGetKey (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.js:149:13)
at <async> storageGetKey (/extension/chrome/elements/compose.ts:143:19)
at <async> draftSave (/extension/js/common/composer.ts:410:22)
```
