### ISSUE TITLE
IO Error: Lock

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1466]

**Comment by tomholub** [comment]
```
Error: Thrown[object][object Object]
at Function.Store.getGlobal (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/store.js:210:128)
at <async> acctEmailsGet (/extension/js/common/platform/store.ts:320:25)
at <async> migrateGlobal (/extension/js/background_page/migrations.ts:14:29)
at <async> <anonymous> (/extension/js/background_page/background_page.ts:26:2)

e.thrown:
[typeof:object:[object Object]] {"message":"IO error: .../LOCK: No further details. (ChromeMethodBFE: 15::LockFile::1)"}
```
