### ISSUE TITLE
properly handle bg not ready

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1487]
```
Error: BrowserMsg.RawResponse: undefined returned "undefined" result for call _tab_
at processRawMsgResponse (chrome-extension://ddnbojhkjfeodohkdhikggjalbinbaje/js/content_scripts/webmail_bundle.js:7674:24)
at sendResponseAndClearCallback (extensions::messaging:417:9)
at disconnectListener (extensions::messaging:435:9)
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
at dispatchOnDisconnect (extensions::messaging:378:27)
at <async> tabId (/extension/js/common/extension.ts:235:24)
at <async> requiredTabId (/extension/js/common/extension.ts:240:32)
at <async> initInternalVars (/extension/js/content_scripts/webmail/setup_webmail_content_script.ts:66:27)
```

**Comment by tomholub** [comment]
because we already have a mechanism for dealing with that
