### ISSUE TITLE
handle and render attachment check errors in gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1498]

**Comment by tomholub** [comment]
```
Error: (no status text): 200 when GET-ing https://www.googleapis.com/gmail/v1/users/me/messages/1683e63891b1fe17/attachments/.... undefined:
at XMLHttpRequest.r.onreadystatechange (/js/content_scripts/webmail_bundle.js:5686:36)

provided ajax call stack:
at Promise (/js/content_scripts/webmail_bundle.js:5612:33)
at new Promise (<anonymous>)
at Object.attGetChunk (/js/content_scripts/webmail_bundle.js:5610:51)
at GmailElementReplacer.processAtts (/js/content_scripts/webmail_bundle.js:8832:65)
```
