### ISSUE TITLE
better logging of 500 errors

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1500]
The stack trace below is not very useful. Exactly what did the err 500 say? That would be useful.

```
Error: Internal Server Error: 500 when POST-ing https://flowcrypt.com/api/message/upload object:
at Function.Api.ajax (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:599:11)

provided ajax call stack:
at Object.apiCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:679:42)
at Object.apiFcCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:690:56)
at Object.messageUpload (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:501:31)
at Composer.doEncryptFmtSend (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:722:49)
at <async> ajax (/extension/js/common/api/api.ts:670:23)
at <async> apiCall (/extension/js/common/api/api.ts:723:13)
at <async> messageUpload (/extension/js/common/api/api.ts:583:19)
at <async> doEncryptFmtSend (/extension/js/common/composer.ts:788:29)
at <async> encryptSend (/extension/js/common/composer.ts:633:24)

url: ...
```

**Comment by michael-volynets** [comment]
I will take a look at this.

**Comment by tomholub** [comment]
This issue is not very well specified (that's why it's missing `actionable` label), I'll unassign you until it's better specified.
