### ISSUE TITLE
Error: IO error: .../LOCK: Access denied

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1501]
```
Error: IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)
at Function.Store.errCategorize (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/store.js:394:48)
at Object.chrome.storage.local.get.result [as callback] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/chrome.js:32:18)
at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
at handleResponse (extensions::sendRequest:67:7)
```
```
Error
IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/background_page/background_page.htm
```
100x +

**Comment by tomholub** [comment]
The goal is to categorize these so that they get rendered to the user (and not sent to us).

**Comment by tomholub** [comment]
closing as minor
