### ISSUE TITLE
[possibly fixed?] Compose err: Could not find valid key packet for encryption

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1624]
```
Error: Error encrypting message: Could not find valid key packet for encryption in key 7090e7683e4659c7
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33480:15
at async Promise.all (index 2)
at async encryptSessionKey (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33477:21)
at async Message.encrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33434:15)
at async Function.PgpMsg.encrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp.js:723:10)
at async AttUI.collectEncryptAtts (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser.js:1135:24)
at async Composer.encryptSend (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:655:18)
at async Composer.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:642:7)
at <async> encrypt (/extension/js/common/core/pgp.ts:716:41)
at <async> collectEncryptAtts (/extension/js/common/browser.ts:1231:23)
at <async> encryptSend (/extension/js/common/composer.ts:671:24)
```

It's weird such keys make it into the contacts. Maybe the keys since expired while being stored in contacts? To test:
1) create a key that expires in a few minutes (using OpenPGP.js library directly)
2) import into contacts
3) wait a few minutes
4) try to send a message with the key as a recipient's pubkey
5) observe this error

To address this issue, in these situations, the following `Ui.modal.confirm` should show up:
```
Public key registered for email@recipient.com (AB66 7886 ...) is no longer usable. Please reach out to the recipient and ask them to provide you an updated public key. When you receive updated public key from the recipient, you can import it and send the message.

Import updated public key now?

[ok] [cancel]
```

Clicking `cancel` will just dismiss the modal, and I will be back to composing the message.

Clicking `ok` will show `add_pubkey.htm` subpage (similar to what happens when I click "add their pubkey" when a person is missing a pubkey).

There, I will be able to enter a new pubkey and save it, which should replace the public key in contacts. After that, I should be able to send the email.

**Comment by tomholub** [comment]
Actually, this can also happen because your own key since expired.

1) test the same situation, but instead of importing the soon-to-expire key as a contact, import the private key as your own key (set up FlowCrypt with it)
2) wait for it to expire, test...

That means this has two possible solutions:
 - if the problem is caused by recipient's key, do as described above
 - if the problem is caused by my own private/public keypair, show `Ui.modal.warning`:
```
Your private key is no longer usable for encryption.

Please update your private key and import the updated version in FlowCrypt Settings -> Additional Settings -> My Keys -> update.
```

**Comment by tomholub** [comment]
There's a third variation of this problem, when signing:

```
Error: Error signing cleartext message: Could not find valid signing key packet in key eb6a2ee6f7956d90
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33657:13
at async Promise.all (index 0)
at async createSignaturePackets (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33650:3)
at async CleartextMessage.signDetached (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:23500:36)
at async CleartextMessage.sign (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:23484:43)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:34426:17
at async Function.PgpMsg.sign (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp.js:612:19)
at async Composer.signSend (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:699:26)
at async Composer.signSend (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:678:8)
at async Composer.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:640:7)
at <async> sign (/extension/js/common/core/pgp.ts:636:16)
at <async> signSend (/extension/js/common/composer.ts:685:21)
at <async> signSend (/extension/js/common/composer.ts:685:21)
```
But I think we will not be addressing the signing issue yet. Some keys may come without signing capability, and figuring out exactly what is the problem with the key is not always trivial. When the rest of this issue is done, we may create another issue to address this `Could not find valid signing key` err.

**Comment by tomholub** [comment]
I think this situation was somewhat improved now, let's see if this resurfaces

**Comment by tomholub** [comment]
Relevant: #1930 #1895  #1721

**Comment by tomholub** [comment]
This is probably now fixed
