### ISSUE TITLE
update featherlight to latest version

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1625]
maybe they have since resolved the following err that I keep seeing:
```
TypeError: Cannot read property 'naturalWidth' of undefined
at Featherlight.onResize (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/featherlight/featherlight.js:591:31)
at Featherlight.i [as onResize] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:86266)
at Featherlight.<anonymous> (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/featherlight/featherlight.js:96:45)
at Function.each (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:2573)
at globalEventHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/featherlight/featherlight.js:94:5)
at dispatch (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:41772)
at y.handle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:39791)
```
I believe I've made some changes to featherlight css we use (uncommented `.featherlight .featherlight-close-icon`), so if you also update the css, pay attention to see if anything broke or changed in regards to styling, and maybe uncomment it in the same way (or do something appropriate in our own css without changing featherlight css file, for easier updates).

Alternatively we could just ignore the new css version and keep using our own - up to you.

**Comment by tomholub** [comment]
@michael-volynets You said you encountered the error above on the new version. How did you manage to make the error show? I could never reproduce it. Can you still reproduce it?
