### ISSUE TITLE
offer to fix up keys that miss user id packet

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1626]
To reproduce:
1) create a private key with gnupg that does not have any userid
2) try to set up FlowCrypt with it
3) you get:
```
Error: Invalid key: need at least key and user ID packet
at new Key (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:31010:11)
at Object.normalize (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp.js:197:14)
at async KeyImportUi.normalize (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser.js:952:24)
at async KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser.js:923:28)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.js:469:22
```

Such errors should start throwing `KeyCanBeFixed` error, and `renderCompatibilityFixBlockAndFinalizeSetup` should be updated to be able to fix such issues.

Automated test should be added too.

**Comment by tomholub** [comment]
I thought we already did this, but peeking at the code, maybe we don't.

**Comment by wiktor-k** [comment]
Okay, I almost finished this task and found a tiiiiny inconvenience: `openpgp.reformatKey` that can fix these UIDless keys accepts a `Key` parameter... and we can't get the `Key` out of UIDless key because `openpgp.key.readArmored` throws on armored UIDless keys. Of course removing the check:

```js
  if (!this.keyPacket || !this.users.length) {
    throw new Error('Invalid key: need at least key and user ID packet');
  }
```

that is in `Key` constructor "fixes" (workarounds?) the issue as without it we can generate the key without UIDs and then parse and reformat it just fine.

(btw `key.armor()` doesn't seem to exist now but there are direct properties for accessing armored data on keys).

Do you think we should ask OpenPGP.js folks what do they think about making the check configurable or just fork it or maybe there is some kind of other solution I didn't take into account?...

**Comment by tomholub** [comment]
I definitely remember being able to import such keys (as far as parsing / dearmoring them with OpenPGP.js). Maybe the behavior has changed, in which case it would be a regression. That would explain why I thought such keys used to work, but no longer do.

I think the OpenPGP.js team will be open to allow dearmoring such keys without throwing, but throwing later on `k.getPrimaryUser()` or similar. If they are open to this, you can submit a PR to OpenPGP.js and bill us for it.

**Comment by tomholub** [comment]
Here is a similar precedent - it used to check and throw too early, during dearmoring - and the team was willing to push the check until later:

https://github.com/openpgpjs/openpgpjs/pull/1017

**Comment by tomholub** [comment]
Btw I don't think this would be worth a fork if they reject the pr

**Comment by wiktor-k** [comment]
:thinking: The check seems to be introduced in commit b27b01905be3987576f507ff29f0292e5faf4ea6 that was created in 2013. I'll file an issue in OpenPGP.js and we'll see how it goes.

**Comment by tomholub** [comment]
Un-assigning, since it's blocked on OpenPGP.js maintainers
