### ISSUE TITLE
BrowserMsg -1 when upgrading

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1681]
Happened to me, possibly right after upgrading.

It was I think on version 6.7.4, so this would suggest before the previous fix #1628

From this experience it suggests that one more possible cause is that the browser just updated the extension.

> [BrowserMsg() (no status text): -1 when GET-ing blob:moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/bdb8500a-6e2c-48ce-9247-c72dbbbc22da (no body): ] [callerStack] BrowserMsg.sendAwait@moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/js/common/extension.js:103:68 pgpMsgDecrypt@moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/js/common/extension.js:71:27 decryptAndRender@moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/chrome/elements/pgp_block.js:363:27 url: moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/chrome/elements/pgp_block.htm?frameId=frame_hrKDUMedno&message=-----BEGIN%20PGP%20MESSAGE-----%0AVersion%3A%20FlowCrypt%206.7.2%20Gmail%20Encryption%0AComment%3A%20Seamlesslyend%20and%20receive%20encrypted%20email%0A%0AwcFMAzBfgamu0SA1AQ//fDvZVD0xDVcx6DeEf8V5nzsgfYkDxgEmcG86NHzm%0AxWcgg562dOrHnK5SMGtvMqM9syfAP/nvPVW84Cd1MiEnNldSNS0jmp%2Bj4iRC%0A/xqoUYIc8h2P/IYvys7VRjGdC3ZDN/z0ed5ZvDla8XSSTfZ2GytpltoMY0Le%0AbhFvomPnRh6u2eYz9TkE4EoYUa0fu5Iw1qtsAhbH%2BZSxQwu19kYntbF55WPB%0Ax4NVC%2BKik7zIOMm7vQLsnjcrfqf1C3zlpdhpPKiDv5pwIc%2B6h11dcHeyUreY%0AE%2BILmMPYboAbU6fg1Vk%2B9HNKbEBpxxm9KhsecEX4O8dCui9D1nuJxsCiP/3n%0AFt321IknzpumypQyrBymj1%2BO5M7BAFGu4wJOy0IEgi4bjXrMuAkUF37XCqfY%0At2XJdp1UHOtFfBCvORJbUf5dNV4YrTt1ynHe29H1LtiH2K2lbn0jkhx/XNXM%0AZEY0lOD67PwpVGE1WHDCXZmPhzLjLn/E9IC2z57byHhCuX/JQbIKYwdXWQG%2B%0ARBUR/eVzxBE9q1E9uJapEioMwgFuMc0/pHvyhCnZPqWek3nQJDlqFrf0cvxO%0AOQ6kla8v0V3%2BOiyWUIQOXmoIV2yM1OwWo3AJHAcopmUv4DRY8akxUVf0ZGL2%0AsN365KxYcpD7e8eSEy5rKWChbLFW7HeGtxHbbIDC5KDBwEwDnUF6Q2e8E%2BMB%0AB/kARTsSEslvmxIPdaJ3aA9uf6Izk8BOYo9bpBSbifmM5fNMbQ6eZ1AB4abJ%0ACjbFS4zWOP7gIQQ9jw3/LJBKyCdZla6rjDHWjXcztFNwaDWH9LTWKvq7Jvdc%0Av8xq/3ZpxUozABV0N5E6P3gFpfaEzM1S7fkxLyrqxYS%2BRiCDCDjxahBdD7z2%0AJfuh1zTeGLFbzQ1xVnlspyWGCA7kKYGB3O9SSIlWvW/YwkluMIYC56TVi5qe%0AMoD3Mbc324fVbFjtT5vDJ819/ZpW5X6RKKAFv2LA88DcGnG5FN0RcuAVU9Ba%0A6tgSKKznJ%2BJ92ptIDPQlK8hBM0aOHApUvbkgmEEi1JYQ0k8B92fXXGSTpaVT%0A/JgnGJlqFbq3d0B4YDbI/VWyEct%2Becd/vvrVaOmpjwYAVnLZyhepc57URh21%0AJLDRaZx385QYNjNjL/68w7xAoAFJrLrO%0A%3Dq6LS%0A-----END%20PGP%20MESSAGE-----&hasPassword=___cu_false___&msgId=169f7045995a0f8b&senderEmail=humanlowcrypt.com&isOutgoing=___cu_true___&acctEmail=help.cryptup.org%40gmail.com&parentTabId=6%3A0 [/callerStack] [responderStack] url: moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/js/background_page/background_page.htm provided ajax call stack: url: moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/js/background_page/background_page.htm at <async> objUrlConsume (/extension/js/common/browser.ts:51:32) at <async> replaceObjUrlWithBuf (/extension/js/common/extension.ts:330:40) [/responderStack] at <async> decryptAndRender (/extension/chrome/elements/pgp_block.ts:338:27)

**Comment by tomholub** [comment]
it was in private browsing mode
