### ISSUE TITLE
error changing pass phrase

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1919]
```
TypeError: Cannot read property 'length' of null
at MPI.toUint8Array (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41380:32)
at MPI.write (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41367:48)
at write_cleartext_params (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:38726:24)
at SecretKey.encrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:38820:21)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33020:5
at async Promise.all (index 0)
at <async> openpgpKeyEncrypt (/extension/js/common/settings.ts:65:29)
at <async> <anonymous> (/extension/chrome/settings/modules/change_passphrase.ts:89:75)
```
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/change_passphrase.htm

**Comment by tomholub** [comment]
Followup - this could be further improved
