### ISSUE TITLE
Content scripts: Swal is not defined

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2169]
this may be related to #2110 - but experienced on Chrome

![image](https://user-images.githubusercontent.com/6306961/68431460-2c72a380-01aa-11ea-87e4-b94408e82014.png)

The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
webmail_bundle.js:10061 Loading FlowCrypt 7.0.6 for info@nvimp.com
2m=RI4GO,UZdBGe,VOAugd,YesRdb,kL0rjf,saV8oc,u7EXMd:63 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://hangouts.google.com') does not match the recipient window's origin ('https://mail.google.com').
(anonymous) @ m=RI4GO,UZdBGe,VOAugd,YesRdb,kL0rjf,saV8oc,u7EXMd:63
9Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
webmail_bundle.js:10343 Updating FlowCrypt
webmail_bundle.js:10082 Loading FlowCrypt 7.0.6 for info@nvimp.com
webmail_bundle.js:82 ReferenceError: Swal is not defined
    at Object.warning (webmail_bundle.js:7939)
    at webmail_bundle.js:8221
    at new Promise (<anonymous>)
    at Function.BrowserMsg.sendAwait (webmail_bundle.js:8167)
    at Object.storeAcctGet (webmail_bundle.js:8123)
    at Function.Store.getAcct (webmail_bundle.js:695)
    at async GmailElementReplacer.replaceStandardReplyBox (webmail_bundle.js:9886)
    at <async> warning (/extension/js/common/browser.ts:455)
Catch.onErrorInternalHandler @ webmail_bundle.js:82
webmail_bundle.js:86 [Swal is not defined]ReferenceError: Swal is not defined    at Object.warning (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:7939:13)    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:8221:26    at new Promise (<anonymous>)    at Function.BrowserMsg.sendAwait (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:8167:68)    at Object.storeAcctGet (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:8123:46)    at Function.Store.getAcct (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:695:59)    at async GmailElementReplacer.replaceStandardReplyBox (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/content_scripts/webmail_bundle.js:9886:46)    at <async> warning (/extension/js/common/browser.ts:455:13)
webmail_bundle.js:6059 FlowCrypt cannot handle fatal error because: Extension context invalidated. Destroying. Error: storage is undefined
    at webmail_bundle.js:6078
    at new Promise (<anonymous>)
    at storageLocalGet (webmail_bundle.js:6076)
    at Function.Store.getGlobal (webmail_bundle.js:667)
    at Function.Store.saveError (webmail_bundle.js:675)
    at Function.Catch.onErrorInternalHandler (webmail_bundle.js:133)
    at Catch.reportErr (webmail_bundle.js:152)
webmail_bundle.js:10343 Updating FlowCrypt
webmail_bundle.js:117 FlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly.

**Comment by tomholub** [comment]
Happened after I clicked "reload" in `chrome://extensions`. Worked after I hit F5.

**Comment by tomholub** [comment]
It's trying to show a Swal warning, but there's no Swal.

Using Swal directly in content scripts would be annoying to the user anyway, so I'll try to do something else.
