### ISSUE TITLE
Error: Could not find primary user with expired key during setup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2227]
```
Error: Could not find primary user
at Key.getExpirationTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:33036:11)
at async Object.dateBeforeExpiration (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp.js:510:29)
at async Object.usableButExpired (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp.js:496:47)
at async KeyImportUi.checkEncryptionPrvIfSelected (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key_import_ui.js:290:30)
at async KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key_import_ui.js:116:17)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.js:531:37
at <async> dateBeforeExpiration (/extension/js/common/core/pgp.ts:540:26)
at <async> usableButExpired (/extension/js/common/core/pgp.ts:526:22)
at <async> checkEncryptionPrvIfSelected (/extension/js/common/ui/key_import_ui.ts:264:41)
at <async> checkPrv (/extension/js/common/ui/key_import_ui.ts:116:13)
```

**Comment by tomholub** [comment]
waiting for public key sample
