### ISSUE TITLE
standalone - own key expired test flakiness

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2246]
`compose[global:flowcrypt.test.key.new.manual@gmail.com] - standalone - own key expired` fails sometimes when running in CI. I don't know the reason yet.
Here is stack trace:
```
compose[global:flowcrypt.test.key.new.manual@gmail.com] - standalone - own key expired
--
  | ℹ (attempt 1 of 3) Retrying: Error: waiting failed: Elements did not appear: .ui-modal-error
  | ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: .ui-modal-error
  | ℹ (attempt 3 of 3) Failed:   Error: waiting failed: Elements did not appear: .ui-modal-error
  | at ControllablePage.ControllableBase.waitAny (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:106:11)
  | at <anonymous>
  | at <async> waitAny (/test/source/browser/controllable.ts:86:19)
  | at <async> waitForModalAndRespond (/test/source/tests/page_recipe.ts:17:41)
  | at <async> <anonymous> (/test/source/tests/tests/compose.ts:374:126)
  | at <async> <anonymous> (/test/source/browser/browser_pool.ts:152:49)
  |  
  | /home/semaphore/git/flowcrypt-browser/test/source/browser/browser_pool.ts:118


```

**Comment by tomholub** [comment]
I may have fixed this recently on master, by increasing timeout.

**Comment by tomholub** [comment]
here https://github.com/FlowCrypt/flowcrypt-browser/pull/2236

**Comment by michael-volynets** [comment]
I've seen this bug 3 times today.
So it's not really fixed.

**Comment by tomholub** [comment]
Got it

**Comment by tomholub** [comment]
Maybe decreasing parallelism slightly could fix this

**Comment by tomholub** [comment]
One other approach would be to quarantine flakey tests into a separate CI task, where they would be executed serially without any parallelism. That should make them run more reliably.

**Comment by tomholub** [comment]
I'll have a look

**Comment by tomholub** [comment]
It will now run on a separate machine, which should make it run more reliably.
