### ISSUE TITLE
invalid recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2383]
```
Error
The To: field contains invalid emails: Name Surname <name@domain.com>

Please check recipients and try again.
url: moz-extension://be49a97c-92c2-40fe-a6de-4c08994ec104/chrome/elements/compose.htm?isReplyBox=___cu_tr
```

**Comment by tomholub** [comment]
```
EmailProviderApi/this.createMsgObj@moz-extension://be49a97c-92c2-40fe-a6de-4c08994ec104/js/common/api/email_provider/email_provider_api.js:20:27

at <async> createMsgObj (/extension/js/common/api/email_provider/email_provider_api.ts:59:24)
at <async> sendableMsg (/extension/chrome/elements/composer/formatters/signed-msg-mail-formatter.ts:16:16)
at <async> processNewMsg (/extension/chrome/elements/composer/formatters/composer-mail-formatter.ts:15:25)
```
