### ISSUE TITLE
Att bytes already set

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2397]
```
catch.js:77 Error: Att bytes already set
    at Att.setData (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/core/att.js:12:23)
    at downloadDataIfNeeded (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/attachment.js:154:23)
    at async handleDownloadButtonClicked (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/attachment.js:172:21)
    at <async> downloadDataIfNeeded (/extension/chrome/elements/attachment.ts:138:31)

### Catch.reportErr calling stack ###
#     at Function.Catch.formattedStackBlock (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/catch.js:140:44)
#     at Function.Catch.reportErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/catch.js:145:26)
#     at renderErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/attachment.js:74:23)
#     at handleDownloadButtonClicked (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/attachment.js:181:21)
# 
# url: chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/attachment.htm?frameId=frame_LMnbCjwwlW&msgId=15f7f6780c0c7432&name=node-v6.10.0-linux-x64.tar.xz.pgp&type=application%2Fx-xz&size=9377514&attId=ANGjdJ9MemZv3BdPZQF7cUKxwBFLXfn3s0dAF2j43D5e7P8RQwjfxfDSuCrEvF9pDamAFxqSQ97M9Un7qqlnIUtRmW18phY7saWfeawCBBVL00ANOp6bV5r48zAQXYHTsrTzLIh7oH8jXO8d7pMybV3XZByB8qqkfoaE7BPKgrUO949DGx6hePu-nmUNDCsLkOm6cAWOvmefzSF0m0sW0y5mQDWZrcIFed-ZvvsSemy2rqEDejX72GLnxU8C4DU417KX3FmnbichO_H-2qIegcIBlOoMZz8hct9a4P6b2QrU-qpfl8SbKmVS9K0edik8jXW0Kju1EEG5POabOspETWqpfhrgdsKM_EdcGxc-b7N2G9rmHO36FGIYLhz7pPC_VFHTk_L1saD4drV1rUux&isEncrypted=___cu_true___&acctEmail=flowcrypt.compatibility%40gmail.com&parentTabId=2%3A0
# 
######################
```

https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#sent/WhctKJVjQgXRmNJNwxKZQZnNHdcvNDddfgcgklRrGFKNnvsVqKsDvrgmhPHQXxTnmLBhSbq

**Comment by tomholub** [comment]
should be fixed after #2365 #2394 - happens when double-clicking attachment to download
