### ISSUE TITLE
handle `The database connection is closing.` as fatal error (restart browser)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2541]
> [BrowserMsg() sendRawResponse::InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.]Error: BrowserMsg() sendRawResponse::InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at Function.BrowserMsg.jsonToErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:316:15)    at processRawMsgResponse (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:243:35)[callerStack]    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:215:120    at new Promise (<anonymous>)    at Function.BrowserMsg.sendAwait (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:213:18)    at Object.db (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:31:36)    at Function.Store.dbContactSearch (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/store.js:502:47)    at ComposeRecipientsModule.searchContacts (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/compose-modules/compose-recipients-module.js:466:50)    at ComposeView.<anonymous> (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/compose-modules/compose-recipients-module.js:34:32)    at cbWithErrsHandled (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/ui.js:74:48)url: chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/compose.htm?frameId=frame_FbuFrohfuv&acctEmail=flowcrypt.compatibility%40gmail.com&parentTabId=2%3A0[/callerStack][responderStack]Error: sendRawResponse::InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at Function.Catch.rewrapErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/catch.js:29:20)    at Function.BrowserMsg.errToJson (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:307:38)    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:325:63[typeof:Error:InvalidStateError] Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/store.js:522:29    at new Promise (<anonymous>)    at Function.Store.dbContactSearch (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/store.js:521:18)    at Store.dbContactSearch (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/store.js:511:44)    at Function.BgHandlers.dbOperationHandler (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/background_page/bg-handlers.js:26:18)    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/background_page/background_page.js:42:54    at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/browser-msg.js:185:60[/responderStack]### Catch.reportErr calling stack ####     at Function.Catch.formattedStackBlock (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/catch.js:263:44)#     at Function.Catch.reportErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/platform/catch.js:132:26)#     at Object._dispatchErr (chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/ui.js:62:19)#     at chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/js/common/browser/ui.js:76:43# # url: chrome-extension://nhlmpmiobabndkmnhocbgomijbcmiikg/chrome/elements/compose.htm?frameId=frame_FbuFrohfuv&acctEmail=flowcrypt.compatibility%40gmail.com&parentTabId=2%3A0# ######################

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/74084293-a6465180-4a65-11ea-9a0a-cc47d241c720.png)

**Comment by tomholub** [comment]
This is after manually deleting the database in db tools.

Maybe could just reopen the db in bg script instead of showing fatal err.

**Comment by tomholub** [comment]
too much hassle, too little benefit
