### ISSUE TITLE
don't request a welcome message if key is expired / not for encryption

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2722]
We allow users to import expired key or a sign-only key

Currently such key is sent to `/attester/test/welcome` which sends user a welcome message.

Attester will respond with err 500 because it throws trying to encrypt for the key.

1) attester should start returning err 400
2) client should not try to send it if the key not fit for encryption

```
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] Error: Error encrypting message: Could not find valid key packet for encryption in key xxxx
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] [stack] Error: Error encrypting message: Could not find valid key packet for encryption in key b991d30a3612c1d5
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] [stack] at /home/flowcrypt-attester-ts/app/node_modules/openpgp/dist/openpgp.js:33527:15
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] [stack] at <anonymous>
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] [stack] at process._tickCallback (internal/process/next_tick.js:188:7)
Apr 02 12:48:58 fr-leader-a flowcrypt-attester-ts-api-internal.out: [ATTESTER_TS_ERROR] [details] url:POST:/encrypt
```

**Comment by tomholub** [comment]
In this particular issue we only address the client side

**Comment by tomholub** [comment]
This probably doesn't need to be accompanied by any test

**Comment by tomholub** [comment]
There is `Key.usableForEncryption` for this
