### ISSUE TITLE
Temporary add-on installation is not supported in this version of Firefox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2782]
run_firefox

```
...
Applying config file: ./package.json
Running web extension from /home/luke/git/flowcrypt-browser/build/firefox-consumer
Use --verbose or open Tools > Web Developer > Browser Console to see logging

o: Temporary add-on installation is not supported in this version of Firefox (you need Firefox 49 or higher). For older Firefox versions, use --pre-install
    at c.sourceDir [as startFirefoxInstance] (/home/luke/git/flowcrypt-browser/node_modules/web-ext/dist/webpack:/src/extension-runners/firefox-desktop.js:274:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
$ firefox -v
Mozilla Firefox 77.0.1
```

**Comment by tomholub** [comment]
seems to work now

```
$ firefox -v
Mozilla Firefox 79.0
```
