### ISSUE TITLE
Error: Unsupported key type: unknown

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2825]
```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async AddKeyView.addPrivateKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.js:72:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at AddKeyView.addPrivateKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.js:87:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.htm?placement=settings&parentTabId=740%3A0&acctEmail=...
#
######################
```

**Comment by tomholub** [comment]
```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:25:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:40:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken
#
######################
```

```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:25:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:40:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken
#
######################
```

```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:25:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:40:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken
#
######################
```

```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:25:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at SetupImportKeyModule.actionImportPrivateKeyHandle (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-import-key.js:40:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken
#
######################
```
