### ISSUE TITLE
signature verification errors in the background page

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2857]
```
Error: Signature is expired
at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:36705:15

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at Function.PgpMsg.verify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:114:23)
# at async PgpMsg.verifyDetached (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:128:16)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/background_page/background_page.htm
#
######################
```

```
Error: Insecure message hash algorithm: SHA1
at Signature.verify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41159:11)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:36702:24

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at Function.PgpMsg.verify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:114:23)
# at async PgpMsg.verifyDetached (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:128:16)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/background_page/background_page.htm
#
######################
```

Should be communicated to the user, and not reported to us.

add test

**Comment by tomholub** [comment]
Also

```
Error: Message digest did not match
at Signature.verify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:41125:11)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:36702:24

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at Function.PgpMsg.verify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:114:23)
# at async PgpMsg.verifyDetached (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/pgp-msg.js:128:16)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/background_page/background_page.htm
#
######################
```
