### ISSUE TITLE
getTime is not a function

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2862]
```

OXSIDSUCB9_x6env: chrome:ex:prodv 7.8.6 | TypeErrorarmoredPubkey.pubkey.created.getTime is not a functionurl: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_tru
-- | --
```

```
TypeError: armoredPubkey.pubkey.created.getTime is not a function
at EncryptedMsgMailFormatter.encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:153:66)
at EncryptedMsgMailFormatter.encryptDataArmor (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:104:52)
at EncryptedMsgMailFormatter.sendableSimpleTextMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:75:66)
at <async> encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:121:68)
at <async> encryptDataArmor (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:87:29)
at <async> sendableSimpleTextMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:65:34)
at <async> sendableMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:27:23)
at <async> processNewMsg (/extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts:15:32)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:119:31)
# at ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:111:47)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_true___&frameId=frame_oSBQaIrKda&skipClickPrompt=___cu_false___&ignoreDraft=___cu_false___&replyMsgId=...&acctEmail=...&parentTabId=1721714500%3A0#
# 
```

**Comment by wiktor-k** [comment]
Hmm... this is a very interesting bug. I try to reproduce it in Gmail Secure Compose (as it initially appears to be some kind of deserialization issue where probably `created` is a string instead of Date) and test with expired keys (both my own and my recipients) but there are no issues (the expired key stack traces appear but not `created.getTime is not a function`).

I'll split another key and try with a self-sig-less key, maybe that one will reproduce... :factory_worker:

**Comment by tomholub** [comment]
I'll try to get the pubkey from the user

**Comment by wiktor-k** [comment]
That'd be very useful, thank you! :bowing_man:

**Comment by tomholub** [comment]
I don't think we're getting any pubkey anytime soon, will have to attempt a blind fix here.

I'm attaching newest stack traces in case they are helpful.

```

XSIBSFVQCN_x3env: chrome:ex:prodv 7.8.8 | TypeErrorarmoredPubkey.pubkey.created.getTime is not a functionurl: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_fEDZgI
-- | --
```
```
ypeError: armoredPubkey.pubkey.created.getTime is not a function
at EncryptedMsgMailFormatter.encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:153:66)
at EncryptedMsgMailFormatter.encryptDataArmor (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:104:52)
at EncryptedMsgMailFormatter.sendableSimpleTextMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:75:66)
at <async> encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:121:68)
at <async> encryptDataArmor (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:87:29)
at <async> sendableSimpleTextMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:65:34)
at <async> sendableMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:27:23)
at <async> processNewMsg (/extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts:15:32)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:119:31)
# at ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:111:47)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_fEDZgIkbwl&acctEmail=
```

----------------------

```
TypeError: armoredPubkey.pubkey.created.getTime is not a function
at EncryptedMsgMailFormatter.encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:153:66)
at EncryptedMsgMailFormatter.encryptDataArmor (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:104:52)
at EncryptedMsgMailFormatter.sendableSimpleTextMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:75:66)
at <async> encryptMsgAsOfDateIfSomeAreExpiredAndUserConfirmedModal (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:121:68)
at <async> encryptDataArmor (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:87:29)
at <async> sendableSimpleTextMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:65:34)
at <async> sendableMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:27:23)
at <async> processNewMsg (/extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts:15:32)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:119:31)
# at ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:111:47)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_true___&frameId=frame_RAGSjcAtmp&skipClickPrompt=___cu_false___&ignoreDraft=___cu_false___&replyMsgId=XXX&acctEmail=YYY&parentTabId=238%3A0#
#
######################
```

```

**Comment by tomholub** [comment]
This is interesting - a different page - contacts this time:

```
TypeError
_r.expiration.getTime is not a function
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/contacts.htm?placement=s
```

```
TypeError: _r.expiration.getTime is not a function
at ContactsView.actionRenderViewPublicKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/contacts.js:134:279)
at <async> actionRenderViewPublicKeyHandler (/extension/chrome/settings/modules/contacts.ts:117:45)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at Object._dispatchErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/ui.js:63:19)
# at r.catch.e (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/ui.js:77:43)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/contacts.htm?placement=settings&parentTabId=158987701%3A0&acctEmail=dayramosprofissional2014%40gmail.com#
#
######################
```

**Comment by wiktor-k** [comment]
Yeah, I've got a hunch that this is due to JSON serialization: I bet the dates there are strings (because Date objects JSON-serialize to strings) and not nulls/undefineds because the error message is different there.

There are two things we could do: 1) enrich error messages to display what the object is by inserting try/catch and throw more details, deploy it on prod and then observe errors. 2) assume I'm correct and covert all dates to numbers (unix epoch) and rewrite things around it.

What do you think about this approach?

**Comment by tomholub** [comment]
I'm good with either of the two approaches. I typically do the first approach when I have no clue, and second approach when I have a reasonable guess which is easy to implement.

This case is somewhere in between, hard to go wrong with either approach.

**Comment by wiktor-k** [comment]
Okay, I'll implement 1) today/tomorrow as I'm moving this week and kind of short on time but I'll start with 2) next week as this is a bigger change and I'll be available again in August.

**Comment by tomholub** [comment]
I have not seen too many errors yet - about 30 so far - so it's ok to wait until you are settled again. Thanks!

**Comment by tomholub** [comment]
@seisvelas have you experienced this on latest master? I haven't released the merged code yet.

**Comment by seisvelas** [comment]
A support email reported this problem: https://mail.google.com/mail/u/5/#search/getTime/FMfcgxwJWrXHzQHPZZFZDZFnhvhqPxnB

I asked for their pubkey but they didn't know how to get it, so I sent them instructions. They do have a public key hosted on the Attester:

```pgp
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: FlowCrypt [BUILD_REPLACEABLE_VERSION] Gmail Encryption
Comment: Seamlessly send and receive encrypted email

xjMEXnk13BYJKwYBBAHaRw8BAQdA3akAApLqe6RvsllPJRAt9AqArQAz/RDO
r2PP2SfbA/PNLUR5bGFuIEdhbWxleSA8ZHlsYW4uZ2FtbGV5QGFkdmlzb3J5
Y2xvdWQuY29tPsJ3BBAWCgAfBQJeeTXcBgsJBwgDAgQVCAoCAxYCAQIZAQIb
AwIeAQAKCRDgAV3Tv5YfxXW6AQCVirHykiQBXzsypr6PC8tg4+DAtpwZY1l0
/BbAJcu2EQEAtn1Ec8g73AVZBEQlR2bITpGFa0K0aLT2ve8nrvRqVgDOOARe
eTXcEgorBgEEAZdVAQUBAQdABRg59eMb9aL2C9H98g7nD9wobudJDREHyzit
Rqvph0oDAQgHwmEEGBYIAAkFAl55NdwCGwwACgkQ4AFd07+WH8U9eQD/fzEf
5yidAPWgFf1EKjDtd7wn4q2qHs1+IHDXSsCKjNsA/1sb8oLWtMU3yqbsQFcb
dTAmnWk9gIhjp6TwL466cQwI
=45Lr
-----END PGP PUBLIC KEY BLOCK-----
```

I'll update with the pubkey they have stored at FlowCrypt Settings -> Additional Settings -> Public Key if they respond. Or if we release the code, I'll update the user.

**Comment by seisvelas** [comment]
When I download the Firefox extension from the homepage I get 7.8.7

:o 

Perhaps something went wrong wrt updating the version number?

**Comment by tomholub** [comment]
I haven't actually done the update. Now I have, here's how to check:
1) find latest version commit (now showing 7.8.9) https://github.com/FlowCrypt/flowcrypt-browser/commits/master
2) check https://flowcrypt.com/api/update/downloads or https://flowcrypt.com/api/update/firefox (showing 7.8.9)
3)  check https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc (but here it tends to get stuck in review for a few hours to a few days, so it will show old version)

However the homepage is a bit trickier, because I also need to do a server deploy (this should be improved - the website should use the https://flowcrypt.com/api/update/downloads to update the firefox download link, so that I don't have to immediately deploy to servers when we have a new version)

**Comment by tomholub** [comment]
homepage now shows 7.8.9. Chrome will take a while to be approved.. and even then, for now I did a 15% deployment. So it may take a while before it gets to chrome users. I'll go ahead and close this again.
