### ISSUE TITLE
Error updating expired encryption key

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2867]
From support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJWXcxfJCWWxxmVgKDBZNMrVzn

According to the client:

---

```
When trying to update my primary PGP key I encountered an error through the Chrome browser extension. I used my proper key + passphrase (copy-pasted from a password manager to reduce errors) and had to open console a there was no indication that it passed or failed.

Key was exported using the following command:

`gpg --output private.pgp --armor --export-secret-key 'martin.lowe@eclipse-foundation.org'`

JS console stack:
[Decryption failed - key packet was already decrypted]Error: Decryption failed - key packet was already decrypted    
at Function.PgpKey.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/pgp-key.js:111:27)    
at MyKeyUpdateView.updatePrivateKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/my_key_update.js:77:39)    
at <async> decrypt (/extension/js/common/core/pgp-key.ts:138:26)    
at <async> updatePrivateKeyHandler (/extension/chrome/settings/modules/my_key_update.ts:73:36)
### Catch.reportErr calling stack ###
#     at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
#     at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
#     at Object._dispatchErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/ui.js:63:19)
#     at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/ui.js:77:43
# 
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/my_key_update.htm?acctEmail=martin.lowe%40eclipse-foundation.org&parentTabId=183%3A0
# 
###################### 

I don't think I'm using the extension wrong, so this seems to be an issue extension side. 

Some additional info since you might need it:

Browser: Chromium - Version 83.0.4103.97 (Official Build) Arch Linux (64-bit)
OS: Manjaro, kernel 5.6.16-1-MANJARO (up-to date with rolling release stable)
Extension version: 7.7.9

```

---

In my own case, I can update a key just fine using that interface. I'm not sure what's going wrong for this user.

**Comment by tomholub** [comment]
These issues are very hard to debug because it would be super helpful to have the actual key that causes the issue. But that is not possible, it's a private key. Once in a while I succeed in having the user create another similar key that also causes the same issue, which really helps.

But maybe it can be fixed using the stack alone (without a test).
