### ISSUE TITLE
 'contacts' is not a known object store name

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2872]
Support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXBxDNkNFKcHwpmmjlNxDZdNv

A user setup FlowCrypt on a new device, where they get the following error:

> Error setting up FlowCrypt:
> 
> FlowCrypt encountered an error with unknown cause. (Error: BrowserMsg() sendRawResponse::NotFoundError: IDBDatabase.transaction: 'contacts' is not a known object store name)
> 
> Please write human@flowcrypt.com if this happens repeatedly.

**Comment by tomholub** [comment]
Was it on Firefox? maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1653276

**Comment by tomholub** [comment]
Yes this appears on firefox, found the stack.

```
BrowserMsg.jsonToErr@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:402:15
processRawMsgResponse@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:315:39


[callerStack]
BrowserMsg.sendAwait@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:285:22
db@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:33:36
ContactStore.save@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/store/contact-store.js:107:44
SetupView/this.saveKeysAndPassPhrase@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/chrome/settings/setup.js:191:36


url: moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/chrome/settings/setup.htm~censored:idToken

[/callerStack]

[responderStack]
Catch.rewrapErr@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/catch.js:29:20
BrowserMsg.errToJson@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:393:38
BrowserMsg.sendRawResponse/<@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:412:67


[typeof:Error:NotFoundError] IDBDatabase.transaction: 'contacts' is not a known object store name

ContactStore.save/<@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/store/contact-store.js:115:27
ContactStore.save@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/store/contact-store.js:114:22
ContactStore.save/<@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/store/contact-store.js:111:70
ContactStore.save@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/store/contact-store.js:111:39
BgHandlers.dbOperationHandler@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/background_page/bg-handlers.js:28:22
@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/background_page/background_page.js:43:58
BrowserMsg.bgListen/</<@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/browser/browser-msg.js:232:60

at <async> save (/extension/js/common/platform/store/contact-store.ts:131:23)
at <async> save (/extension/js/common/platform/store/contact-store.ts:131:23)
at <async> dbOperationHandler (/extension/js/background_page/bg-handlers.ts:18:37)
[/responderStack]

at <async> sendAwait (/extension/js/common/browser/browser-msg.ts:360:29)
at <async> save (/extension/js/common/platform/store/contact-store.ts:131:23)
at <async> saveKeysAndPassPhrase (/extension/chrome/settings/setup.ts:200:33)

### Catch.reportErr calling stack ###
# Catch.reportErr@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/platform/catch.js:132:26
# ApiErr.reportIfSignificant@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/js/common/api/error/api-error.js:173:15
# SetupRecoverKeyModule/this.actionRecoverAccountHandler@moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/chrome/settings/setup/setup-recover-key.js:76:28
#
#
# url: moz-extension://46f51537-393e-4d4f-a3f1-c85722e69a77/chrome/settings/setup.htm~censored:idToken
#
######################
	delete
```

**Comment by tomholub** [comment]
I'd double check that setup still works on Firefox, and if yes, ask the user to delete FlowCrypt and try again. Could have been a rare error.

**Comment by seisvelas** [comment]
I suggested they reinstall flowcrypt and haven't received a response yet. Since they haven't gotten back to us and we can't reproduce the error, I'll close this (for now)...
