### ISSUE TITLE
setup backup recovery: TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2878]
Support email: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXCHHgRPDxfjbXfhFFDgNLpsr

> 
> I have the FlowCrypt extension installed in Windows 10 Chrome browser - works fine.  Got the new Edge browser and installed the FlowCrypt extension from the Chrome web store.  When I try to activate the extension in Edge, it asks me to enter my PassPhrase and I do so.  It results in the below error message.  My PassPhrase is certainly not "null".  Please advise.  TIA.
> 
> FlowCrypt encountered an error with unknown cause. (TypeError: Cannot read property 'length' of null)
> 
> Please write human@flowcrypt.com if this happens repeatedly

**Comment by tomholub** [comment]
Edge is chromium based, so there's a chance we could support it. Currently the answer should be that Edge is not yet supported (only Chrome and Firefox), but you can point to this issue in case user wants to know when we resolve it.

**Comment by tomholub** [comment]
Marking as actionable, though not high priority - one of us will eventually test this on Edge and and see if it can be fixed.

**Comment by Terafugia** [comment]
When you get it working on Edge(ium), It'd be great if you would release the extension on Microsoft's (new) Edge-Addon service they have released. For the sake of consistency, profile etc.

**Comment by tomholub** [comment]
We can at least test on Edge for Linux which is available here https://www.microsoftedgeinsider.com/en-us/download/?platform=linux-deb

@danishnavid008 please try to run the extension on Edge, and see if any problems arise. Please document the problems here. After that, please attempt fixing them, and ask for help when you need guidance.

**Comment by danishnavid008** [comment]
@tomholub Okay, I'll test the extension and document the problems if I got any.

**Comment by danishnavid008** [comment]
@tomholub, I tested the extension on Edge in ubuntu as well and windows 10 but I don't found any problems.

**Comment by tomholub** [comment]
Does it use exactly the same manifest as the chrome extension? Which functionality was tested? (setup - compose email - attachments - receive email - read attachments - etc).

Another thing to try is keeping pass phrase in session vs in storage (see Security settings), then test all of the above.

Which Windows version of Edge were you testing on, and which Linux version?

**Comment by tomholub** [comment]
@Terafugia which Edge version were you testing on and how? Thank you!

**Comment by danishnavid008** [comment]
> Does it use exactly the same manifest as the chrome extension? Which functionality was tested? (setup - compose email - attachments - receive email - read attachments - etc).
> 
> Another thing to try is keeping pass phrase in session vs in storage (see Security settings), then test all of the above.
> 
> Which Windows version of Edge were you testing on, and which Linux version?

Yes, It uses exactly the same manifest as the chrome extension. I've tested all the functionalities (setup - compose email - attachments - recieve email - read attachments - 30 day trials etc)

Okay I'll try to keep the pass phrase in session vs in storage and test it again.

For Linux I've used `microsoft-edge-dev_88.0.705.9-1_amd64.deb` and for windows 10 `87.0.664.55 (Official build)`

**Comment by danishnavid008** [comment]
> @Terafugia which Edge version were you testing on and how? Thank you!

First I installed the extension from the web store and then I tested each functionality. After testing it, I removed the extension and tried the local build and tested it each functionality.

**Comment by tomholub** [comment]
I found a similar error, it does not look specific to Edge. We'll have the user re-try on Chrome.

```
  TypeError: Cannot read property 'length' of null                                                                                                                  | chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm  
      at MPI.toUint8Array (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:42758:32)                                                             |                                                                                                       
      at MPI.write (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:42745:48)                                                                    |                                                                                                       
      at write_cleartext_params (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:40011:24)                                                       |                                                                                                       
      at SecretKey.write (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:40139:31)                                                              |                                                                                                       
      at List.write (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:39203:33)                                                                   |                                                                                                       
      at Key.armor (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/openpgp.js:34504:59)                                                                    |                                                                                                       
      at Function.OpenPGPKey.wrap (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/openpgp-key.js:254:40)                             |                                                                                                       
      at async Function.OpenPGPKey.decryptKey (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/openpgp-key.js:85:9)                   |                                                                                                       
      at async Function.PgpKey.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/pgp/openpgp-key.js:630:16)                        |                                                                                                       
      at async Function.KeyUtil.checkPassPhrase (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:199:16)                           |                                                                                                       
      at <async> wrap (/extension/js/common/core/crypto/pgp/openpgp-key.ts:150:23)                                                                                  |                                                                                                       
      at <async> decryptKey (/extension/js/common/core/crypto/pgp/openpgp-key.ts:49:29)                                                                             |                                                                                                       
      at <async> decrypt (/extension/js/common/core/crypto/pgp/openpgp-key.ts:450:26)                                                                               |                                                                                                       
      at <async> checkPassPhrase (/extension/js/common/core/crypto/key.ts:226:34)                                                                                   |                                                                                                       
                                                                                                                                                                    |                                                                                                       
  ### Catch.reportErr calling stack ###                                                                                                                             |                                                                                                       
  #     at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)                              |                                                                                                       
  #     at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)                                        |                                                                                                       
  #     at Function.ApiErr.reportIfSignificant (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/error/api-error.js:173:15)                        |                                                                                                       
  #     at SetupRecoverKeyModule.actionRecoverAccountHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-recover-key.js:76:28) |                                                                                                       
  #                                                                                                                                                                 |                                                                                                       
  # url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken                                                             |                                                                                                       
  #                                                                                                                                                                 |                                                                                                       
  ######################                                                                                                                                            |                                                                                                       
                                                                                                                                                                    |                                                                                                       
```

**Comment by danishnavid008** [comment]
@tomholub I'll look into it and fix it.

**Comment by tomholub** [comment]
I'm not sure you can fix this one all that easily, this error happens in a cryptographic library. Please look into other issues, I'll report this to the maintainers.

**Comment by tomholub** [comment]
I'm closing this without a fix. If we encounter it again or more frequently, we should reopen.
