### ISSUE TITLE
npm run-script build fails to run

### ISSUE THREAD

**Issue by yantakus** [FlowCrypt/flowcrypt-browser#3047]
Getting the following error (copied from logs):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run-script', 'build' ]
2 info using npm@6.14.8
3 info using node@v13.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle flowcrypt-browser@7.9.5~prebuild: flowcrypt-browser@7.9.5
6 info lifecycle flowcrypt-browser@7.9.5~build: flowcrypt-browser@7.9.5
7 verbose lifecycle flowcrypt-browser@7.9.5~build: unsafe-perm in lifecycle true
8 verbose lifecycle flowcrypt-browser@7.9.5~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yan/Projects/flowcrypt-browser/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle flowcrypt-browser@7.9.5~build: CWD: /Users/yan/Projects/flowcrypt-browser
10 silly lifecycle flowcrypt-browser@7.9.5~build: Args: [ '-c', './build.sh' ]
11 silly lifecycle flowcrypt-browser@7.9.5~build: Returned: code: 64  signal: null
12 info lifecycle flowcrypt-browser@7.9.5~build: Failed to exec build script
13 verbose stack Error: flowcrypt-browser@7.9.5 build: `./build.sh`
13 verbose stack Exit status 64
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid flowcrypt-browser@7.9.5
15 verbose cwd /Users/yan/Projects/flowcrypt-browser
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "build"
18 verbose node v13.12.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 64
22 error flowcrypt-browser@7.9.5 build: `./build.sh`
22 error Exit status 64
23 error Failed at the flowcrypt-browser@7.9.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 64, true ]
```

Any ideas?

**Comment by tomholub** [comment]
Is this on windows? If you are on windows, you would have to use WSL2 for the build script to work.

If you are on any system that supports a recent version of bash (Ubuntu), then this is some other bug.

**Comment by tomholub** [comment]
There is also this thing called Git Bash for windows, if we can make it work using that, maybe the windows user would not need to install anything at all and it would all just work by using git bash from npm (I'm not familiar with this, just heard about it).

**Comment by yantakus** [comment]
I'm on Mac OS.

**Comment by yantakus** [comment]
Is there a requirement for bash version? I-m on `3.2`.

**Comment by tomholub** [comment]
Last time I checked, MacOS had an old version of bash that didn't support glob patterns like `**`:
```
( cd $SRCDIR && cp -r --parents ./**/*.{js,htm,css,ttf,woff2,png,svg,txt} ../build/chrome-enterprise )
```
The easiest would be if there would be a way for you to install (homebrew?) a newer version of bash on the side, which could be used by the build scripts but would not affect your system bash in general.

If this cannot be done, then the commands using `**` would have to be rewritten to be compatible with older versions of bash.

**Comment by tomholub** [comment]
I think it needed version 4 but I cannot find a reference now

**Comment by tomholub** [comment]
Here they say v4 https://www.linuxjournal.com/content/globstar-new-bash-globbing-option

**Comment by yantakus** [comment]
I've upgraded bash to v5 per this instruction: https://www.shell-tips.com/mac/upgrade-bash/ but I'm still getting the same error:

![image](https://user-images.githubusercontent.com/2179726/96419489-e537c400-11fc-11eb-80be-e94ba2e1c96e.png)

**Comment by tomholub** [comment]
Can you please copy-paste the whole output?

**Comment by yantakus** [comment]
```
Yan:flowcrypt-browser yan$ npm run-script build

> flowcrypt-browser@7.9.5 build /Users/yan/Projects/flowcrypt-browser
> ./build.sh

+ shopt -s globstar
+ [[ 0 == 1 ]]
+ [[ 0 == 1 ]]
+ rm -rf ./build
+ npx tsc --project ./conf/tsconfig.tooling.json
+ mkdir -p ./build/generic-extension-wip
+ pids+=($!)
+ node ./build/tooling/tsc-compiler --project ./tsconfig.json
+ pids+=($!)
+ for pid in "${pids[@]}"
+ wait 881
+ node ./build/tooling/tsc-compiler --project ./conf/tsconfig.content_scripts.json
+ for pid in "${pids[@]}"
+ wait 882
+ mkdir -p ./build/generic-extension-wip/lib/
+ mkdir -p ./build/generic-extension-wip/css/
+ cp node_modules/dompurify/dist/purify.js ./build/generic-extension-wip/lib/purify.js
+ cp node_modules/jquery/dist/jquery.min.js ./build/generic-extension-wip/lib/jquery.min.js
+ cp node_modules/openpgp/dist/openpgp.js ./build/generic-extension-wip/lib/openpgp.js
+ cp node_modules/openpgp/dist/openpgp.worker.js ./build/generic-extension-wip/lib/openpgp.worker.js
+ cp node_modules/sweetalert2/dist/sweetalert2.js ./build/generic-extension-wip/lib/sweetalert2.js
+ cp node_modules/sweetalert2/dist/sweetalert2.css ./build/generic-extension-wip/css/sweetalert2.css
+ cp node_modules/iso-8859-2/iso-8859-2.js ./build/generic-extension-wip/lib/iso-8859-2.js
+ cp node_modules/zxcvbn/dist/zxcvbn.js ./build/generic-extension-wip/lib/zxcvbn.js
+ cp node_modules/squire-rte/build/squire-raw.js ./build/generic-extension-wip/lib/squire-raw.js
+ cp node_modules/clipboard/dist/clipboard.js ./build/generic-extension-wip/lib/clipboard.js
+ cp node_modules/@flowcrypt/fine-uploader/fine-uploader/fine-uploader.js ./build/generic-extension-wip/lib/fine-uploader.js
+ cp node_modules/filesize/lib/filesize.js ./build/generic-extension-wip/lib/filesize.js
+ cp node_modules/pdfjs-dist/build/pdf.js ./build/generic-extension-wip/lib/pdf.js
+ cp node_modules/pdfjs-dist/build/pdf.worker.js ./build/generic-extension-wip/lib/pdf.worker.js
+ mkdir -p ./build/generic-extension-wip/lib/bootstrap
+ cp node_modules/bootstrap/dist/js/bootstrap.min.js ./build/generic-extension-wip/lib/bootstrap/bootstrap.min.js
+ cp node_modules/bootstrap/dist/css/bootstrap.min.css ./build/generic-extension-wip/lib/bootstrap/bootstrap.min.css
+ cd ./extension
+ cp -r --parents ./lib/blob.js ./lib/emailjs/emailjs-addressparser.js ./lib/emailjs/emailjs-mime-builder.js ./lib/emailjs/emailjs-mime-codec.js ./lib/emailjs/emailjs-mime-parser.js ./lib/emailjs/emailjs-mime-types.js ./lib/emailjs/emailjs-stringencoding.js ./lib/emailjs/punycode.js ./lib/forge.js ./chrome/dev/ci_pgp_host_page.htm ./chrome/dev/ci_unit_test.htm ./chrome/dev/export.htm ./chrome/elements/add_pubkey.htm ./chrome/elements/attachment.htm ./chrome/elements/attachment_preview.htm ./chrome/elements/backup.htm ./chrome/elements/compose.htm ./chrome/elements/passphrase.htm ./chrome/elements/pgp_block.htm ./chrome/elements/pgp_pubkey.htm ./chrome/elements/shared/attach.template.htm ./chrome/elements/subscribe.htm ./chrome/emails/email_intro.template.htm ./chrome/popups/default.htm ./chrome/popups/select_account.htm ./chrome/settings/fatal.htm ./chrome/settings/inbox/inbox.htm ./chrome/settings/index.htm ./chrome/settings/initial.htm ./chrome/settings/modules/account.htm ./chrome/settings/modules/add_key.htm ./chrome/settings/modules/auth_denied.htm ./chrome/settings/modules/backup.htm ./chrome/settings/modules/change_passphrase.htm ./chrome/settings/modules/compatibility.htm ./chrome/settings/modules/contacts.htm ./chrome/settings/modules/debug_api.htm ./chrome/settings/modules/decrypt.htm ./chrome/settings/modules/experimental.htm ./chrome/settings/modules/help.htm ./chrome/settings/modules/keyserver.htm ./chrome/settings/modules/my_key.htm ./chrome/settings/modules/my_key_update.htm ./chrome/settings/modules/my_key_user_ids.htm ./chrome/settings/modules/security.htm ./chrome/settings/modules/test_passphrase.htm ./chrome/settings/setup.htm ./chrome/texts/email_provider_auth_security.htm ./chrome/texts/passphrase_help.htm ./js/background_page/background_page.htm ./css/animate.css ./css/browser-popup.css ./css/cryptup.css ./css/fine-uploader-new.css ./css/hide.css ./css/mobile-menu-styling.css ./css/open-sans.css ./css/settings.css ./css/smime.css ./css/webmail.css ./fonts/Tangerine_Bold.ttf ./fonts/Tangerine_Regular.ttf ./fonts/open-sans/open-sans-v15-light.woff2 ./fonts/open-sans/open-sans-v15-regular.woff2 ./fonts/open-sans/open-sans-v15-semibold.woff2 ./img/fa/fa-cogs-gray.png ./img/fa/fa-cogs-green.png ./img/fa/fa-location-arrow.png ./img/fileformat/excel.png ./img/fileformat/generic.png ./img/fileformat/jpg.png ./img/fileformat/png.png ./img/fileformat/word.png ./img/footer-icon-pubkey-active.png ./img/footer-icon-pubkey-standard.png ./img/guidelined/google-signin-pressed.png ./img/guidelined/google-signin.png ./img/guidelined/microsoft-signin-pressed.png ./img/guidelined/microsoft-signin.png ./img/lock-seamless-bg-alpha.png ./img/logo/browser-extension/19x19x@1x.png ./img/logo/browser-extension/19x19x@2x.png ./img/logo/browser-extension/19x19x@3x.png ./img/logo/browser-extension/38x38x@1x.png ./img/logo/browser-extension/38x38x@2x.png ./img/logo/browser-extension/38x38x@3x.png ./img/logo/flowcrypt-logo-125-27.png ./img/logo/flowcrypt-logo-128-128.png ./img/logo/flowcrypt-logo-16-16.png ./img/logo/flowcrypt-logo-19-19.png ./img/logo/flowcrypt-logo-24-24.png ./img/logo/flowcrypt-logo-32-32.png ./img/logo/flowcrypt-logo-38-38.png ./img/logo/flowcrypt-logo-48-48.png ./img/logo/flowcrypt-logo-64-64.png ./img/red-cross-mark.png ./img/screens/chrome-setup.png ./img/screens/content-settings-advanced-1.png ./img/screens/content-settings-advanced-2.png ./img/screens/content-settings-firefox.png ./img/screens/content-settings-simple.png ./img/svgs/download-link.png ./img/logo/full-logo.svg ./img/logo/logo.svg ./img/material-design-icons/monitor-cellphone.svg ./img/svgs/arrow-start.svg ./img/svgs/backup-header.svg ./img/svgs/caution.svg ./img/svgs/chevron-left-white.svg ./img/svgs/chevron-left.svg ./img/svgs/close-icon-black.svg ./img/svgs/close-icon.svg ./img/svgs/cog-icon-2.svg ./img/svgs/cog-icon.svg ./img/svgs/contact__edit-icon.svg ./img/svgs/contact__remove-icon.svg ./img/svgs/contact__show-icon.svg ./img/svgs/contacts-icon.svg ./img/svgs/download-link-green.svg ./img/svgs/download-link-white.svg ./img/svgs/download-link.svg ./img/svgs/expired-timer.svg ./img/svgs/eyeclosed-icon.svg ./img/svgs/eyeopen-icon.svg ./img/svgs/feedback-header.svg ./img/svgs/feedback-icon.svg ./img/svgs/gmail.svg ./img/svgs/key-icon.svg ./img/svgs/keys-icon.svg ./img/svgs/locked-icon-gray.svg ./img/svgs/locked-icon-green.svg ./img/svgs/locked-icon-orange.svg ./img/svgs/locked-icon.svg ./img/svgs/maximize.svg ./img/svgs/minimize.svg ./img/svgs/minus-solid.svg ./img/svgs/new-email-icon.svg ./img/svgs/new-email.svg ./img/svgs/paperclip-icon.svg ./img/svgs/plus-sign.svg ./img/svgs/plus-solid.svg ./img/svgs/profile-icon.svg ./img/svgs/pub-key-icon.svg ./img/svgs/public-profile.svg ./img/svgs/puzzle.svg ./img/svgs/question-icon-b.svg ./img/svgs/question-icon-white.svg ./img/svgs/question-icon.svg ./img/svgs/repeat-icon.svg ./img/svgs/reply-icon.svg ./img/svgs/security-header.svg ./img/svgs/security-icon.svg ./img/svgs/servers-icon.svg ./img/svgs/settings-cog.svg ./img/svgs/settings-icon.svg ./img/svgs/settings.svg ./img/svgs/shield-icon.svg ./img/svgs/signature-gray.svg ./img/svgs/signature.svg ./img/svgs/spinner-green-large.svg ./img/svgs/spinner-green-small.svg ./img/svgs/spinner-white-small.svg ./img/svgs/stopwatch-icon.svg ./img/svgs/three-dots.svg ./img/svgs/tick.svg ./img/svgs/trash-can-icon.svg ./img/svgs/unlock.svg ./img/svgs/zoom-in.svg ./img/svgs/zoom-out.svg ./changelog.txt ./.web-extension-id ./manifest.json .././build/generic-extension-wip
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
npm ERR! code ELIFECYCLE
npm ERR! errno 64
npm ERR! flowcrypt-browser@7.9.5 build: `./build.sh`
npm ERR! Exit status 64
npm ERR! 
npm ERR! Failed at the flowcrypt-browser@7.9.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yan/.npm/_logs/2020-10-19T08_17_27_527Z-debug.log
Yan:flowcrypt-browser yan$ bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by tomholub** [comment]
can you check if your `cp` command supports `--parents`?
I'm not 100% sure what exactly it does, cp help says this:

```
      --parents                use full source file name under DIRECTORY
```
version
```
$ cp --version
cp (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
```
I think relying on a new enough bash is ok, but requiring that even `cp` has to be of a certain version may be too much. Unless it's really easy for you to update?

**Comment by tomholub** [comment]
I guess maybe `--parents` preserves the relative path when copying nested directory tree like we do.

**Comment by yantakus** [comment]
Mac OS's cp doesn't support `--parents`. Installed GNU cp and made it default as per this instruction: https://stackoverflow.com/a/40431200/3049064 and it works now. `npm run-script build` runs successfully.

**Comment by tomholub** [comment]
Great! Please add instructions on which steps to follow into the readme.
