### ISSUE TITLE
link to show err diagnostics when attachment cannot be decrypted

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3199]
That way errors like this could be better surfaced to the user instead of reported to us:

```
Error: Session key decryption failed.
at AttachmentPreviewView.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.js:100:23)
at async AttachmentPreviewView.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.js:24:55)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/view.js:27:21
at <async> decrypt (/extension/chrome/elements/attachment_preview.ts:84:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:299:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at AttachmentPreviewView.AttachmentDownloadView.renderErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment.js:123:23)
# at AttachmentPreviewView.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.js:66:26)
# at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/view.js:27:21
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.htm
#
######################
```

It should say:

> Failed to decrypt: <a href="#">see error details</a>

Then if I click `see error details`, it should show me full diagnostics of the problem. At the least, the object that got returned by the decrypt function if any (pretty formatted), and the above exception stack, etc.

Similar button should be added to message decrypt errors.

Clicking the link should show a modal using `Ui.modal.warning` on the host (parent) page.

**Comment by tomholub** [comment]
There is an email named `Here are the encrypted images` in `flowcrypt.compatibility` account that you can test this on.

To design a mock test for this, you will want to follow these steps:

```ts
  /**
   * This is the proper way to add messages to mock api for testing:
   *   1) log into flowcrypt.compatibility@gmail.com
   *   2) go to Settings -> Inbox and find your message
   *   3) click "download api export"
   *   4) save the json file to exported-messages folder
   */
  private exportedMsgsPath = './test/source/mock/google/exported-messages/';
```

That will then cause the mock to start serving this message. You can then have the tests be done in the "secure inbox" part of the app (instead of Gmail webmail) since mocks only allow you to test on that one.
