### ISSUE TITLE
Cannot read property 'stopKeydownPropagation' of undefined

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3511]
```
TypeError
Cannot read property 'stopKeydownPropagation' of undefined
url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/index.htm

TypeError: Cannot read property 'stopKeydownPropagation' of undefined
at keydownHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/sweetalert2.js:3126:21)
at globalState.keydownHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/sweetalert2.js:3086:16)

### Catch.reportErr calling stack ###
# at Function.Catch.formatExceptionForReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:245:90)
# at Catch.onErrorInternalHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:71:29)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/index.htm
#
######################
```

**Comment by tomholub** [comment]
Seems to be a sweetalert2 issue
