### ISSUE TITLE
The To: field contains invalid emails: www.somedomain.com

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3557]
```
The To: field contains invalid emails: www.somedomain.com

Please check recipients and try again.
```

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm

The report is about secure compose window of a new message, not a reply.

```
Error: The To: field contains invalid emails: www.somedomain.com

Please check recipients and try again.
at new SendableMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/sendable-msg.js:52:19)
at Function.SendableMsg.create (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/sendable-msg.js:120:16)
at async Function.SendableMsg.createSendableMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/sendable-msg.js:110:16)
at async Function.SendableMsg.createPgpInline (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/sendable-msg.js:74:16)
at async EncryptedMsgMailFormatter.sendableSimpleTextMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:88:28)
at async EncryptedMsgMailFormatter.sendableMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.js:35:28)
at async ComposeDraftModule.draftSave (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-draft-module.js:123:42)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-draft-module.js:33:28
at <async> create (/extension/js/common/api/email-provider/sendable-msg.ts:90:26)
at <async> createSendableMsg (/extension/js/common/api/email-provider/sendable-msg.ts:78:37)
at <async> createPgpInline (/extension/js/common/api/email-provider/sendable-msg.ts:48:34)
at <async> sendableSimpleTextMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:67:34)
at <async> sendableMsg (/extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts:29:23)

### Catch.reportErr calling stack ###
# at Function.Catch.formatExceptionForReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:245:90)
# at Function.Catch.onErrorInternalHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:71:29)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:78:11)
# at ComposeDraftModule.draftSave (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-draft-module.js:187:35)
# at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-draft-module.js:33:28
#
######################
```

**Comment by tomholub** [comment]
To reproduce, enter some nonsense domain and hit enter.

**Comment by tomholub** [comment]
I got one more: `some@email.com;`
