### ISSUE TITLE
running tests locally

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3865]
I am getting an error on most test that requires a passphrase. Maybe there is some sort of config that I need based on `Config.key()` that I've missed during the inital setup of the project.

```
(attempt 1 of 1) Failed:   TypeError: Cannot read property 'passphrase' of undefined
          at Function.SetupPageRecipe.recover (/home/mart/project/flowcrypt-browser/test/source/tests/page-recipe/setup-page-recipe.ts:208:69)
          at Function.BrowserRecipe.setUpCommonAcct (/home/mart/project/flowcrypt-browser/test/source/tests/tooling/browser-recipe.ts:60:7)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:73:9
          at /home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:70:5
          at <async> recover (/test/source/tests/page-recipe/setup-page-recipe.ts:205:26)
          at <async> setUpCommonAcct (/test/source/tests/tooling/browser-recipe.ts:57:34)
          at <async> <anonymous> (../test/source/test.ts:70:53)
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
```

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-browser/issues/3864#issuecomment-888919390_

**Comment by tomholub** [comment]
Just want to confirm, this is when running them locally?

**Comment by martgil** [comment]
Yes Tom, only at my local machine. Most of the tests that request for `k = Config.key('acctEmaiil')` and requesting  `k.passphrase` will return undefined on most test for me.

**Comment by tomholub** [comment]
Could you give me an example of one specific test - I'll try it locally.

**Comment by tomholub** [comment]
Which OS are you using

**Comment by martgil** [comment]
>Could you give me an example of one specific test - I'll try it locally.
I'm using Ubuntu Linux. 

>Could you give me an example of one specific test - I'll try it locally.
The test on `test/source/test/settings.ts` with its first test `settings - my own emails show as contacts` will throw this error in my case. But basically any test that requires the some passphrase will be getting some error as well :
```
 ℹ (attempt 1 of 1) Failed:   TypeError: Cannot read property 'passphrase' of undefined
          at Function.SetupPageRecipe.recover (/home/mart/project/flowcrypt-browser/test/source/tests/page-recipe/setup-page-recipe.ts:208:69)
          at Function.BrowserRecipe.setUpCommonAcct (/home/mart/project/flowcrypt-browser/test/source/tests/tooling/browser-recipe.ts:60:7)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:73:9
          at /home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:70:5
          at <async> recover (/test/source/tests/page-recipe/setup-page-recipe.ts:205:26)
          at <async> setUpCommonAcct (/test/source/tests/tooling/browser-recipe.ts:57:34)
          at <async> <anonymous> (../test/source/test.ts:70:53)
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
          ```

**Comment by tomholub** [comment]
@limonte please, when you have a chance, please help Mart diagnose the issue so that he can run tests locally.

**Comment by limonte** [comment]
@martgil can you confirm that you have the `test-secrets.json` file inside of the `test` directory and it is readable?

```bash
flowcrypt-browser $ ls -l test/test-secrets.json                                                                                                                 
-rw-r--r-- 1 limonte 75516 Jul 23 22:38 test/test-secrets.json
```

(please paste your output of `ls -l test/test-secrets.json`)

**Comment by martgil** [comment]
Hello, sir @limonte. Glad to meet you 😊 ! I never thought that I will ever meet the creator of sweetalert2 🙇🙏🏼.

Here, It says the `test-secrets.json` was missing from my project.
![image](https://user-images.githubusercontent.com/46025304/128835370-166beea4-7d00-47cb-9a9e-9dd0882cd729.png)

Thanks Again, sir!

**Comment by tomholub** [comment]
I'll send it to you.

**Comment by limonte** [comment]
> Hello, sir @limonte. Glad to meet you 😊 ! I never thought that I will ever meet the creator of sweetalert2 🙇🙏🏼.
> 
> Here, It says the `test-secrets.json` was missing from my project.
> ![image](https://user-images.githubusercontent.com/46025304/128835370-166beea4-7d00-47cb-9a9e-9dd0882cd729.png)
> 
> Thanks Again, sir!

Nice to meet you too Mart. Download the `test-secrets.json` file to the `test` folder, and after that running tests locally should work for you 🚀

**Comment by martgil** [comment]
Hi @tomholub and @limonte,

The test is now running correctly without any errors. 

Thank you so much!
