### ISSUE TITLE
CI is failing for master branch, Sks lookup pubkey - from live host

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4009]
Even though the last merged PR #4000 was green, the master branch is failing now, probable some external issue:

https://flowcrypt.semaphoreci.com/workflows/a02184aa-adb7-42b9-ba63-13603e52be5a?pipeline_id=fa6286b1-37ee-4d26-a604-bcd3da242029

```[unit-Sks.js] Sks lookup pubkey - from live host
    ℹ Expected unit test to return "pass" but got: "unit test threw something:Error: Expecting key.id=6BF16EE1ECE7A66C4B6636DF0C9C2E6A4D273C6F but got 8B8A05A2216EE6E4C5EE3D540D5688EBF3102BE7
      Error: Expecting key.id=6BF16EE1ECE7A66C4B6636DF0C9C2E6A4D273C6F but got 8B8A05A2216EE6E4C5EE3D540D5688EBF3102BE7
          at __puppeteer_evaluation_script__:11:11
          at async __puppeteer_evaluation_script__:4:24"
    ℹ (attempt 1 of 1) Failed:   Error: unit test threw something:Error: Expecting key.id=6BF16EE1ECE7A66C4B6636DF0C9C2E6A4D273C6F but got 8B8A05A2216EE6E4C5EE3D540D5688EBF3102BE7
          at /home/semaphore/git/flowcrypt-browser/test/source/tests/unit-browser.ts:45:17
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7
          at /home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11)
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5
          at <async> <anonymous> (/test/source/tests/unit-browser.ts:25:91)
          at <async> <anonymous> (../test/source/test.ts:71:53)
```

**Comment by tomholub** [comment]
Thanks - the test may be updated to accept either of the two fingerprints.
