### ISSUE TITLE
live test "mail.google.com - secure reply btn, reply draft" fails often

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4020]
```
  ✖ mail.google.com - secure reply btn, reply draft [ALL RETRIES FAILED for mail.google.com - secure reply btn, reply draft] 10:07
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `[data-test="send-btn-note"]` failed: timeout 20000ms exceeded 10:07
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="input-body"] 10:07
    ℹ (attempt 3 of 3) Failed:   Error: waiting failed: Elements did not appear: [data-test="input-body"] 10:07
          at ControllablePage.ControllableBase.waitAny (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:84:11) 10:07
          at ControllablePage.ControllableBase.waitForContent (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:317:5) 10:07
          at pageHasSecureDraft (/home/semaphore/git/flowcrypt-browser/test/source/tests/gmail.ts:65:9) 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/tests/gmail.ts:273:22 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61 10:07
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11) 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5 10:07
          at <async> waitAny (/test/source/browser/controllable.ts:64:19) 10:07
          at <async> waitForContent (/test/source/browser/controllable.ts:316:26) 10:07
          at <async> pageHasSecureDraft (/test/source/tests/gmail.ts:62:31) 10:07
          at <async> <anonymous> (/test/source/tests/gmail.ts:256:101) 10:07
  10:07
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
```

**Comment by tomholub** [comment]
Related issue from before: #3481
