### ISSUE TITLE
support very large files (hundreds of mb) + avoid tool.str.from_uint8

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#433]
```
RangeError: Invalid string length
    at Array.join (native)
    at uint8_to_str (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1261:12)
    at XMLHttpRequest.request.onload (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:271:20)
```

Converstion to string maxes out at 256MB depending on JS implementation. Avoid converting to str.

**Comment by tomholub** [comment]
This also fails on large strings

```js
  function crypto_armor_clip(text) {
    if(text && text.indexOf('-----BEGIN') !== -1 && text.indexOf('-----END') !== -1) {
      var match = text.match(/(-----BEGIN PGP (MESSAGE|SIGNED MESSAGE)-----[^]+-----END PGP (MESSAGE|SIGNATURE)-----)/gm);
      return(match !== null && match.length) ? match[0] : null;
    }
  }
```

like this

```
    RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (native)
    at String.match (native)
    at extract_armored_message_from_text (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1097:22)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/gmail_api.js:370:41
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/gmail_api.js:245:9
    at Object.success (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/gmail_api.js:27:13)
    at i (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27914)
    at z (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:12120)
```

**Comment by tomholub** [comment]
not yet
