### ISSUE TITLE
error when gmail service is not setup on google account yet

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#435]
```
Error: gmail_api_message_send error response from gmail
    at cryptup_error_log (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:128:11)
    at Object.handle_send_message_error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/gmail_elements/shared/compose.js:307:7)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/gmail_elements/new_message.js:34:21
    at Object.error (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/gmail_api.js:38:17)
    at i (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27151)
    at Object.fireWith [as rejectWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27914)
    at z (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:12145)
    at XMLHttpRequest.<anonymous> (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:15680)


details: {"readyState":4,"responseText":"{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"failedPrecondition\",\n    \"message\": \"Mail service not enabled\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"Mail service not enabled\"\n }\n}\n","responseJSON":{"error":{"errors":[{"domain":"global","reason":"failedPrecondition","message":"Mail service not enabled"}],"code":400,"message":"Mail service not enabled"}},"status":400,"statusText":"error","_error":{"errors":[{"domain":"global","reason":"failedPrecondition","message":"Mail service not enabled"}],"code":400,"message":"Mail service not enabled"}}
```

**Comment by tomholub** [comment]
already fixed 
```js
    isMailOrAcctDisabled: (e: any): boolean => {
      if (Api.err.isBadReq(e) && typeof e.responseText === 'string') {
        return e.responseText.indexOf('Mail service not enabled') !== -1 || e.responseText.indexOf('Account has been deleted') !== -1;
      }
      return false;
    },
```
