### ISSUE TITLE
live tests are broken

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4432]

**Comment by tomholub** [comment]
Some pass, but some are failing. Example:

```ts
 mail.google.com - send rich-text encrypted message 12:28
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `div.z0[class*="_destroyable"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 2 of 3) Retrying: TimeoutError: waiting for selector `div.z0[class*="_destroyable"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 3 of 3) Failed:   TimeoutError: waiting for selector `div.z0[class*="_destroyable"]` failed: timeout 20000ms exceeded 12:28
          at new WaitTask (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34) 12:28
          at DOMWorld.waitForSelectorInPage (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26) 12:28
          at Object.internalHandler.waitFor (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) 12:28
          at DOMWorld.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29) 12:28
          at Frame.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:949:51) 12:28
          at Page.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33) 12:28
          at ControllablePage.ControllableBase.waitAll (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:82:43) 12:28
          at Function.BrowserRecipe.openGmailPage (/home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/tooling/browser-recipe.js:105:29) 12:28
          at async Function.BrowserRecipe.openGmailPageAndVerifyComposeBtnPresent (/home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/tooling/browser-recipe.js:129:27) 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/gmail.js:221:35 12:28
          at <async> waitAll (/test/source/browser/controllable.ts:46:19) 12:28
          at <async> openGmailPage (/test/source/tests/tooling/browser-recipe.ts:33:32) 12:28
          at <async> openGmailPageAndVerifyComposeBtnPresent (/test/source/tests/tooling/browser-recipe.ts:51:58) 12:28
          at <async> <anonymous> (/test/source/tests/gmail.ts:165:104) 12:28
          at <async> <anonymous> (../test/source/test.ts:71:53) 12:28
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49) 12:28
  [ALL RETRIES FAILED for mail.google.com - send rich-text encrypted message] 12:28
  › BrowserPool.processTestError (build/test/test/source/browser/browser-pool.js:209:19) 12:28
  › BrowserPool.withNewBrowserTimeoutAndRetry (build/test/test/source/browser/browser-pool.js:191:30) 12:28
  › async build/test/test/source/test.js:92:13 12:28


  mail.google.com - multiple compose windows, saving/opening compose draft 12:28
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `[class^="open_draft_"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 2 of 3) Retrying: TimeoutError: waiting for selector `[class^="open_draft_"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 3 of 3) Failed:   TimeoutError: waiting for selector `[class^="open_draft_"]` failed: timeout 20000ms exceeded 12:28
          at new WaitTask (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34) 12:28
          at DOMWorld.waitForSelectorInPage (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26) 12:28
          at Object.internalHandler.waitFor (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) 12:28
          at DOMWorld.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29) 12:28
          at Frame.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:949:51) 12:28
          at Page.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33) 12:28
          at ControllablePage.ControllableBase.waitAll (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:82:43) 12:28
          at ControllablePage.ControllableBase.waitAndClick (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:392:32) 12:28
          at /home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/gmail.js:412:33 12:28
          at runMicrotasks (<anonymous>) 12:28
          at <async> waitAll (/test/source/browser/controllable.ts:46:19) 12:28
          at <async> waitAndClick (/test/source/browser/controllable.ts:276:24) 12:28
          at <async> <anonymous> (/test/source/tests/gmail.ts:311:126) 12:28
          at <async> <anonymous> (../test/source/test.ts:71:53) 12:28
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49) 12:28
  [ALL RETRIES FAILED for mail.google.com - multiple compose windows, saving/opening compose draft] 12:28
  › BrowserPool.processTestError (build/test/test/source/browser/browser-pool.js:209:19) 12:28
  › BrowserPool.withNewBrowserTimeoutAndRetry (build/test/test/source/browser/browser-pool.js:191:30) 12:28
  › async build/test/test/source/test.js:92:13 12:28


  mail.google.com - plain reply draft 12:28
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `[data-tooltip="Reply"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 2 of 3) Retrying: TimeoutError: waiting for selector `[data-tooltip="Reply"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 3 of 3) Failed:   TimeoutError: waiting for selector `[data-tooltip="Reply"]` failed: timeout 20000ms exceeded 12:28
          at new WaitTask (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34) 12:28
          at DOMWorld.waitForSelectorInPage (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26) 12:28
          at Object.internalHandler.waitFor (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) 12:28
          at DOMWorld.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29) 12:28
          at Frame.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:949:51) 12:28
          at Page.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33) 12:28
          at ControllablePage.ControllableBase.waitAll (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:82:43) 12:28
          at ControllablePage.ControllableBase.waitAndClick (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:392:32) 12:28
          at /home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/gmail.js:453:33 12:28
          at runMicrotasks (<anonymous>) 12:28
          at <async> waitAll (/test/source/browser/controllable.ts:46:19) 12:28
          at <async> waitAndClick (/test/source/browser/controllable.ts:276:24) 12:28
  12:28
          at <async> <anonymous> (../test/source/test.ts:71:53) 12:28
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49) 12:28
  [ALL RETRIES FAILED for mail.google.com - plain reply draft] 12:28
  › BrowserPool.processTestError (build/test/test/source/browser/browser-pool.js:209:19) 12:28
  › BrowserPool.withNewBrowserTimeoutAndRetry (build/test/test/source/browser/browser-pool.js:191:30) 12:28
  › async build/test/test/source/test.js:92:13 12:28


  mail.google.com - secure reply btn, reply draft 12:28
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `[data-test="secure-reply-button"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 2 of 3) Retrying: TimeoutError: waiting for selector `[data-test="secure-reply-button"]` failed: timeout 20000ms exceeded 12:28
    ℹ (attempt 3 of 3) Failed:   TimeoutError: waiting for selector `[data-test="secure-reply-button"]` failed: timeout 20000ms exceeded 12:28
          at new WaitTask (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34) 12:28
          at DOMWorld.waitForSelectorInPage (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26) 12:28
          at Object.internalHandler.waitFor (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) 12:28
          at DOMWorld.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29) 12:28
          at Frame.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:949:51) 12:28
          at Page.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33) 12:28
          at ControllablePage.ControllableBase.waitAll (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:82:43) 12:28
          at ControllablePage.ControllableBase.waitAndClick (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:392:32) 12:28
          at /home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/gmail.js:381:33 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/test.js:98:21 12:28
          at <async> waitAll (/test/source/browser/controllable.ts:46:19) 12:28
          at <async> waitAndClick (/test/source/browser/controllable.ts:276:24) 12:28
          at <async> <anonymous> (/test/source/tests/gmail.ts:286:101) 12:28
          at <async> <anonymous> (../test/source/test.ts:71:53) 12:28
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49) 12:28
  [ALL RETRIES FAILED for mail.google.com - secure reply btn, reply draft] 12:28
  › BrowserPool.processTestError (build/test/test/source/browser/browser-pool.js:209:19) 12:28
  › BrowserPool.withNewBrowserTimeoutAndRetry (build/test/test/source/browser/browser-pool.js:191:30) 12:28
  › async build/test/test/source/test.js:92:13 12:28


  mail.google.com - plain reply to encrypted and signed messages 12:28
    ℹ (attempt 1 of 3) Retrying: Error: Element not found: [data-tooltip="Reply"] 12:28
    ℹ (attempt 2 of 3) Retrying: Error: Element not found: [data-tooltip="Reply"] 12:28
    ℹ (attempt 3 of 3) Failed:   Error: Element not found: [data-tooltip="Reply"] 12:28
          at ControllablePage.ControllableBase.click (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:191:27) 12:28
          at async ControllablePage.ControllableBase.waitAndClick (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/controllable.js:398:25) 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/tests/gmail.js:432:17 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/test.js:98:21 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/browser-pool.js:169:44 12:28
          at async BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/build/test/test/source/browser/browser-pool.js:167:29) 12:28
          at async /home/semaphore/git/flowcrypt-browser/build/test/test/source/test.js:92:13 12:28
          at <async> click (/test/source/browser/controllable.ts:137:17) 12:28
          at <async> waitAndClick (/test/source/browser/controllable.ts:276:24) 12:28
          at <async> <anonymous> (/test/source/tests/gmail.ts:332:116) 12:28
          at <async> <anonymous> (../test/source/test.ts:71:53) 12:28
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49) 12:28
  [ALL RETRIES FAILED for mail.google.com - plain reply to encrypted and signed messages]
```
