### ISSUE TITLE
Message decryption is broken in brave browser

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#4472]
After update to Brave v1.39.111 (https://brave.com) Flowcrypt extension fails to decrypt all mails, shows this error instead:
<img width="395" alt="Screenshot 2022-05-26 at 12 13 01" src="https://user-images.githubusercontent.com/1062093/170457661-9559768d-59e9-46fe-8208-ec8afbc7153a.png">

Attachment decryption works well.

**Comment by martgil** [comment]
Hello @sosnovsky - thanks for your report!

I'm getting the same error message with the latest brave browser 1.39.111. I'm unsure what causes it but in the meantime, you can read decrypt and read the message through view it at the web extension page (encrypted inbox) - I've tested it and it works.

<img width="883" alt="Screen Shot 2022-05-27 at 5 08 01 PM" src="https://user-images.githubusercontent.com/46025304/170668930-4d690c74-b265-41d4-8c24-09374e0a4754.png">

Sorry for the inconvenience 🙏

**Comment by sosnovsky** [comment]
@martgil thanks for the help! But it seems `encrypted inbox` doesn't work for me too - it loads inbox, but when I try to open any thread (both - encrypted and non-encrypted) I got this error:

```
Failed to load thread due to the following error:
    at GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google-auth.js:99:50)
    at Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadModify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/gmail.js:57:24)
    at async InboxActiveThreadModule.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:50:21)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox.htm?acctEmail=***&threadId=180fd3d64622cd57


provided ajax call stack:
    at GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google-auth.js:99:50)
    at Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadModify (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/gmail.js:57:24)
    at async InboxActiveThreadModule.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:50:21)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox.htm?acctEmail=***&threadId=180fd3d64622cd57


responseText(0, 1000):
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Insufficient Permission",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "caribou.api.proto.MailboxService.ModifyThread",
          "service": "gmail.googleapis.com"
        }
      }
    ]
  }
}


payload(0, 1000):
[typeof:string] {"removeLabelIds":["UNREAD"],"addLabelIds":[]}
    at <async> ajax (/extension/js/common/api/shared/api.ts:64:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/email-provider/gmail/google-auth.ts:102:53)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:21:28)
    at <async> threadModify (/extension/js/common/api/email-provider/gmail/gmail.ts:56:24)

### Catch.reportErr calling stack ###
#     at Catch.formatExceptionForReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:262:90)
#     at Catch.onErrorInternalHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:76:29)
#     at Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:92:18)
#     at InboxActiveThreadModule.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:63:31)
# 
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/inbox/inbox.htm?acctEmail=***&threadId=180fd3d64622cd57
# 
######################
```

**Comment by martgil** [comment]
Hello @sosnovsky - thanks for sharing the error. You may go to FlowCrypt settings > additional settings > experimental > reset <your-account> and set it up again. It should resolve your issue and should be able to read the message.

**Comment by martgil** [comment]
Reports from other Brave browser users:

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGKWDLTQXtwwPKrZXcJSwvnWS

**Comment by sosnovsky** [comment]
@martgil works well for me now, probably some bug was fixed on brave browser side.

**Comment by martgil** [comment]
Glad to hear that @sosnovsky thanks for letting us know :)

> probably some bug was fixed on brave browser side.

Looks like it is. I tried opening a test encrypted + signed message and it works on the same version `1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)`
![image](https://user-images.githubusercontent.com/46025304/172323304-155167fc-0221-4e91-839c-8f83c958ccb8.png)

Thanks again!
