### ISSUE TITLE
broken mocked test

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4688]
```
  ✖ compose - reply all - from === acctEmail [ALL RETRIES FAILED for compose - reply all - from === acctEmail] 04:40
    ℹ (attempt 1 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="replied-to"] 04:40
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="replied-to"] 04:40
    ℹ (attempt 3 of 3) Failed:   /home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:91 04:40
          throw Error(`waiting failed: Elements did not appear: ${selectors.join(',')}`); 04:40
                ^ 04:40
      Error: waiting failed: Elements did not appear: [data-test="replied-to"] 04:40
          at ControllablePage.ControllableBase.waitAny (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:91:11) 04:40
          at ControllablePage.ControllableBase.waitForContent (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:328:5) 04:40
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/tests/compose.ts:1692:7) 04:40
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7) 04:40
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:144:61) 04:40
          at BrowserPool.BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:144:11) 04:40
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5) 04:40
          at <async> waitAny (/test/source/browser/controllable.ts:71:19) 04:40
          at <async> waitForContent (/test/source/browser/controllable.ts:327:26) 04:40
          at <async> <anonymous> (/test/source/tests/compose.ts:1680:93) 04:40
          at <async> <anonymous> (../test/source/test.ts:71:53) 04:40
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:144:49)
```

example https://flowcrypt.semaphoreci.com/jobs/0af49698-7502-499a-ac53-ff80d59192a5

Likely clicking the previous click a little too early.

**Comment by tomholub** [comment]
Actually failed on both consumer and enterprise, so it's possibly just broken.

```
  ✖ compose - reply all - from === acctEmail [ALL RETRIES FAILED for compose - reply all - from === acctEmail] 06:05
    ℹ (attempt 1 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="replied-to"] 06:05
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="replied-to"] 06:05
    ℹ (attempt 3 of 3) Failed:   /home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:91 06:05
          throw Error(`waiting failed: Elements did not appear: ${selectors.join(',')}`); 06:05
                ^ 06:05
      Error: waiting failed: Elements did not appear: [data-test="replied-to"] 06:05
          at ControllablePage.ControllableBase.waitAny (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:91:11) 06:05
          at runMicrotasks (<anonymous>) 06:05
          at runNextTicks (node:internal/process/task_queues:61:5) 06:05
          at processTimers (node:internal/timers:499:9) 06:05
          at ControllablePage.ControllableBase.waitForContent (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:328:5) 06:05
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/tests/compose.ts:1692:7) 06:05
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7) 06:05
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:144:61) 06:05
          at BrowserPool.BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:144:11) 06:05
          at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5) 06:05
          at <async> waitAny (/test/source/browser/controllable.ts:71:19) 06:05
          at <async> waitForContent (/test/source/browser/controllable.ts:327:26) 06:05
          at <async> <anonymous> (/test/source/tests/compose.ts:1680:93) 06:05
          at <async> <anonymous> (../test/source/test.ts:71:53) 06:05
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:144:49)
```

**Comment by ioanmo226** [comment]
I also experienced this issue while doing #4626 and after I added timeout like below, I didn't experience again.
Did you experience recently?

![image](https://user-images.githubusercontent.com/77344191/190248698-7b558bd4-f8ee-46ab-bf6d-d5f03df24544.png)

**Comment by tomholub** [comment]
That sleep wouldn't help. `waitForContent` already waits up to 20 seconds for the content to appear.

You could try increasing the `delay: 1` to `delay: 2` but it's not entirely clear if that would help either.

Would be good to see the screenshot of the failed test. From https://storage.googleapis.com/p8ejr437e40a1hc10jpmsp5q2wfx83/artifacts/jobs/0af49698-7502-499a-ac53-ff80d59192a5/debugHtmlAttachment-0.html?Expires=1663186659&GoogleAccessId=artifacthub%40semaphore2-prod-artifacts.iam.gserviceaccount.com&Signature=uvvHoe%2BYD98dS9xt%2FcJM1uWhD24V9zjCSAdAobAt37gzH%2FLPjsaNJq1dsSCCoLbkHW9D%2B2INBQHweHgPC3kba%2B7BQKQLE36h%2FBNCngjvNYxlyYwXvp8%2BddtQjXJZjdt9g5eNRCOE83TxofT0Ul0Sm%2BRit68emG7FYiNVq3fhldF%2F%2Fg0YhUaVVEGfIYHO05st1GX%2FT3McGQAumRBZP4i2QDR7QEVZ6HPtRq9PUgUM8GIe6%2BEMIss7QBGXGN%2BTBrTaVyTi9q92pLAmtYgPa%2BK6EOYiun45t2tAv6gI0ubYQ47YKF7ncy6m1WXhXP8nfk2LEOCTcvKJwG2Qo%2BgDthn8qQ%3D%3D&response-content-disposition=inline&response-content-type=text/html;%20charset=utf-8# it shows 

![image](https://user-images.githubusercontent.com/6306961/190250400-7eaeccc2-b761-4a9d-96f6-3760b75e1e21.png)

So that delay may not help either, hard to say.

One way to debug it more properly would be to add more logs on what happens when one presses the send button, like these logs from the above artifact:

```
log: [qYbvu] ** input_text giving focus to(<input id="input_password" autocomplete="off" placeholder="message password" tabindex="5" data-test="input-password" style="color: rgb(209, 72, 54);">)
log: [qYbvu] ** send_btn receiving focus from(<input id="input_password" autocomplete="off" placeholder="" tabindex="5" data-test="input-password" style="color: rgb(49, 162, 23);">)
log: [qYbvu] ** send_btn giving focus to(undefined)
```

That will give you more info. You can leave the logs in even after you've figured it out, since they only show for debugging.
