### ISSUE TITLE
`accountUpdate` misbehaves when used on a FES-bound account

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4739]
`accountUpdate` isn't supported for FES setups. However,
there is an option to update password-encrypted expiration for such setups too, and this results in a error and UI displays the update spinner forever.

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/4733#discussion_r996416677_

**Comment by rrrooommmaaa** [comment]
![image](https://user-images.githubusercontent.com/23335944/196028757-030aca24-4369-4c7c-9331-5a277af103ba.png)

```
catch.js:62 Error: Account update not implemented when using FlowCrypt Enterprise Server
    at EnterpriseServer.accountUpdate (enterprise-server.js:146:23)
    at AccountServer.accountUpdate (account-server.js:43:31)
    at async SecurityView.onDefaultExpireUserChange (security.js:111:17)
    at <async> accountUpdate (chrome-extension://aekceebhpkdkofaffkgleeniffikdoal/extension/js/common/api/account-servers/enterprise-server.ts:146:25)
    at <async> accountUpdate (chrome-extension://aekceebhpkdkofaffkgleeniffikdoal/extension/js/common/api/account-server.ts:46:25)
    at <async> onDefaultExpireUserChange (chrome-extension://aekceebhpkdkofaffkgleeniffikdoal/extension/chrome/settings/modules/security.ts:104:38)
```

**Comment by rrrooommmaaa** [comment]
Also see #4738

**Comment by tomholub** [comment]
could hide these two lines when using fes
