### ISSUE TITLE
User cannot setup: Mail service not enabled

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4838]
An enterprise user encounters an error and is unable to setup FlowCrypt for that particular account. The errors summary says `Mail service not enabled`

<summary>Error details:<details>

```

          Below are technical details about the error. This may be useful for debugging.

Error string: Error: error: 400 when GET-ing https://www.googleapis.com/gmail/v1/users/me/settings/sendAs object:  -> Mail service not enabled

Error stack:     at GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.fetchAcctAliases (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/gmail.js:401:29)
    at async Settings.fetchAcctAliasesFromGmail (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:566:26)
    at async Settings.refreshSendAs (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:47:31)
    at async SetupRenderModule.renderInitial (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-render.js:22:25)
    at async Settings.promptToRetry (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:312:24)
    at async SetupRenderModule.renderInitial (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-render.js:27:32)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken


provided ajax call stack:
    at GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.fetchAcctAliases (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/gmail.js:401:29)
    at async Settings.fetchAcctAliasesFromGmail (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:566:26)
    at async Settings.refreshSendAs (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:47:31)
    at async SetupRenderModule.renderInitial (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-render.js:22:25)
    at async Settings.promptToRetry (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/settings.js:312:24)
    at async SetupRenderModule.renderInitial (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup/setup-render.js:27:32)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/setup.htm~censored:idToken


responseText(0, 1000):
{
  "error": {
    "code": 400,
    "message": "Mail service not enabled",
    "errors": [
      {
        "message": "Mail service not enabled",
        "domain": "global",
        "reason": "failedPrecondition"
      }
    ],
    "status": "FAILED_PRECONDITION"
  }
}


payload(0, 1000):
[typeof:object:[object Object]] {}
    at <async> ajax (/extension/js/common/api/shared/api.ts:64:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/email-provider/gmail/google-auth.ts:102:53)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:21:28)
    at <async> fetchAcctAliases (/extension/js/common/api/email-provider/gmail/gmail.ts:328:28)
    at <async> fetchAcctAliasesFromGmail (/extension/js/common/settings.ts:483:45)
    at <async> refreshSendAs (/extension/js/common/settings.ts:46:32)

Ajax response:
{
  "error": {
    "code": 400,
    "message": "Mail service not enabled",
    "errors": [
      {
        "message": "Mail service not enabled",
        "domain": "global",
        "reason": "failedPrecondition"
      }
    ],
    "status": "FAILED_PRECONDITION"
  }
}

End of Ajax response

```

</details></summary>

**Comment by martgil** [comment]
@tomholub possibly the admin from Google console has disabled the account? or Gmail is not enabled for this user?

**Comment by tomholub** [comment]
Indeed this sounds like a problem on their end. Are they even able to use Gmail app, for example?

**Comment by martgil** [comment]
> The account I used is disabled on Gmail but has access to Google
calendar.

@tomholub looks like you're right. The account used is disabled on Gmail.
