### ISSUE TITLE
fix mail.google.com/chat live gmail test fail

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#4942]
currently failing on `master` branch with error:
```
✘ [fail]: mail.google.com/chat [ALL RETRIES FAILED for mail.google.com/chat] 02:48
205    ℹ (attempt 1 of 3) Retrying: ProtocolError: Waiting for selector `.w6VTHd, .wLBAL` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object 02:48
206    ℹ (attempt 2 of 3) Retrying: ProtocolError: Waiting for selector `.w6VTHd, .wLBAL` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object 02:48
207    ℹ (attempt 3 of 3) Failed:   ProtocolError: Waiting for selector `.w6VTHd, .wLBAL` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object 02:48
208          at <anonymous> (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer-core/src/common/Connection.ts:400:16) 02:48
209          at new Promise (<anonymous>) 02:48
210          at CDPSessionImpl.send (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer-core/src/common/Connection.ts:396:12) 02:48
211          at ExecutionContext._ExecutionContext_evaluate (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer-core/src/common/ExecutionContext.ts:290:44) 02:48
212          at JSHandle.evaluateHandle (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer-core/src/common/JSHandle.ts:152:12) 02:48
213          at WaitTask.rerun (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer-core/src/common/WaitTask.ts:163:22) 02:48
214          at <async> waitAll (/test/source/browser/controllable.ts:59:19) 02:48
215          at <async> waitAndClick (/test/source/browser/controllable.ts:309:24) 02:48
216          at <async> google (/test/source/tests/page-recipe/oauth-page-recipe.ts:42:25) 02:48
217          at <async> openSettingsLoginButCloseOauthWindowBeforeGrantingPermission (/test/source/tests/tooling/browser-recipe.ts:20:79) 02:48
218          at <async> <anonymous> (/test/source/tests/gmail.ts:113:33) 02:48
219          at <async> <anonymous> (../test/source/test.ts:74:55)
```

**Comment by sosnovsky** [comment]
Looks like it was some temporary issue, test passes well now ✅
