### ISSUE TITLE
Test sometimes timeout

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5050]
Tests sometimes timeout with below error
```
....
google-mock listening on 4589100:08
google-mock listening on 4089700:08
got contacts size 101:19
url:GET:/gmail/v1/users/me/messages/?format=metadata /home/semaphore/git/flowcrypt-browser/test/source/mock/lib/mock-util.ts:1204:31
export const parseResourceId = (url: string) => url.match(/\/([a-zA-Z0-9\-_]+)(\?|$)/)![1];04:31
                                                                                       ^04:31
TypeError: Cannot read properties of null (reading '1')04:31
    at parseResourceId (/home/semaphore/git/flowcrypt-browser/test/source/mock/lib/mock-util.ts:12:88)04:31
    at /gmail/v1/users/me/messages/? (/home/semaphore/git/flowcrypt-browser/test/source/mock/google/google-endpoints.ts:224:33)04:31
    at LoggedApi.Api.handleReq (/home/semaphore/git/flowcrypt-browser/test/source/mock/lib/api.ts:130:39)04:31
    at runMicrotasks (<anonymous>)04:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)04:31
    at <async> '/gmail/v1/users/me/messages/?' (/test/source/mock/google/google-endpoints.ts:220:35)04:31
    at <async> handleReq (/test/source/mock/lib/api.ts:121:24)
```

**Comment by rrrooommmaaa** [comment]
> TypeError: Cannot read properties of null (reading '1')04:31

Not sure what the reason for this is, possibly some bug, but regarding timeout -- what I see is `compose - saving and rendering a draft with RTL text (rich text)` fails as `Saved` indication doesn't appear, I filed issue #5052 and proposed a fix.

**Comment by rrrooommmaaa** [comment]
Let me have a look at this particular issue

**Comment by rrrooommmaaa** [comment]
This url `/gmail/v1/users/me/messages/?format=metadata` is missing a msgId: 
Should be: `/gmail/v1/users/me/messages/${mdgId}?format=metadata`

**Comment by rrrooommmaaa** [comment]
@sosnovsky Can we find out which test caused this hook to fail?
Perhaps, since the port number is dedicated to a test during its execution, we can keep a port->test_name mapping, and dump the necessary info to the logs if not already?

**Comment by rrrooommmaaa** [comment]
or we should catch it and re-throw `HttpClientErr`

**Comment by sosnovsky** [comment]
> This url `/gmail/v1/users/me/messages/?format=metadata` is missing a msgId:
> Should be: `/gmail/v1/users/me/messages/${msgId}?format=metadata`

Real Gmail API returns list of messages when `msgId` isn't specified (I tested https://www.googleapis.com/gmail/v1/users/me/messages/?format=metadata url), so we should update mock API to have the same behavior.

> @sosnovsky Can we find out which test caused this hook to fail?
> Perhaps, since the port number is dedicated to a test during its execution, we can keep a port->test_name mapping, and dump the necessary info to the logs if not already?

Probably we can use debug info from semaphore for checking which test caused this fail - [debug file](https://storage.googleapis.com/p8ejr437e40a1hc10jpmsp5q2wfx83/artifacts/jobs/11f93653-f3fb-487c-bb27-89df408c2681/debugHtmlAttachment-0.html?Expires=1680509824&GoogleAccessId=artifacthub%40semaphore2-prod-artifacts.iam.gserviceaccount.com&Signature=0LwJB%2BGj5mbPFZ3F3UY0iSPffjMLCF7MsgssTHzZQY28dwopf26wjotW8uOqvRo2Rz%2BBOiK5igeMrwaaMIX0RqOhAq0FCoAYLfRr6JL6y3SjRAu8%2B18V6PQlhPnfFPS1g0oFuN0gINhnAhcUifMyCOXPfJL%2BJUJJEQrm%2FU7uCUgsqtDYMv5kXBIL5YybLEoXUzBVRotag62Nc5UuBHApy5cg6rwpeSiIkiBl6BjziMFiXzHvS6aO8KMIr0ZAerQTLSMMDzBAz97XuRZVxjEtq5bDxuHMsj2VSD8eI3w8%2FjVhGQpwuozCVSEvISp6QTllOK4DE9ZTl0X24SSvGnJNIg%3D%3D&response-content-disposition=inline&response-content-type=text/html;%20charset=utf-8)

But for this case I think we should just update Gmail mock API to not throw error when there is no `msgId` in URL.

**Comment by sosnovsky** [comment]
@rrrooommmaaa have you worked on this task? As it seems tests currently failing mostly because of this issue

**Comment by rrrooommmaaa** [comment]
> Real Gmail API returns list of messages when `msgId` isn't specified (I tested https://www.googleapis.com/gmail/v1/users/me/messages/?format=metadata url), so we should update mock API to have the same behavior.

As far as I know, the extension never deliberately tries to get a list of messages with this call, so this must be a bug. We can make a temporary support of this operation as part of PR #5053, and leave this issue to be researched and fixed separately. The aim of the mock API is not to mimick Gmail API in full, but to warn us about suspicious calls.

**Comment by sosnovsky** [comment]
> As far as I know, the extension never deliberately tries to get a list of messages with this call, so this must be a bug.

Yeah, I think so, but haven't noticed any code changes which can lead to this call.

> We can make a temporary support of this operation as part of PR https://github.com/FlowCrypt/flowcrypt-browser/pull/5053, and leave this issue to be researched and fixed separately.

I'm not 100% sure that this fix will make tests work, it's just my assumption, but we should try to implement it or another temporary solution to make tests pass.
Later we should also improve Semaphore test reporting for easier detection which tests caused such timeouts.

**Comment by rrrooommmaaa** [comment]
> Later we should also improve Semaphore test reporting for easier detection which tests caused such timeouts.

This particular bug isn't causing timeouts, is it? Timeout failure is supposed to be fixed with #5053

**Comment by sosnovsky** [comment]
As I remember tests were still failing in https://github.com/FlowCrypt/flowcrypt-browser/pull/5053, but let's see if they'll pass with your latest commit there

**Comment by sosnovsky** [comment]
Hi @ioanmo226, I didn't notice such test errors recently, looks like it was fixed and we can close this one?
