### ISSUE TITLE
Extract meaningful assertion failure into test result

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#5057]
We need to extract this meaningful piece into the test result:
```
  ✘ [fail]: compose - saving and rendering a draft with RTL text (plain text) [ALL RETRIES FAILED for compose - saving and rendering a draft with RTL text (plain text)]
    ℹ (attempt 1 of 1) Failed:   AssertionError: expected '<div><br></div><div><br></div><div>--…' to include '<div dir="rtl">مرحبا<br></div>'
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/tests/compose.ts:1508:62)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:81:11)
          at BrowserPool.BrowserPool.withNewBrowserTimeoutAndRetry (/home/osboxes/flowcrypt-browser/test/source/browser/browser-pool.ts:113:11)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:75:7)
          at <async> <anonymous> (/test/source/tests/compose.ts:1495:39)
          at <async> <anonymous> (../test/source/test.ts:75:55)
```
The line with `(attempt x of x) Failed` (last attempt)

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/5053#issuecomment-1495979454_

**Comment by rrrooommmaaa** [comment]
There is also strange grouping issue
![image](https://user-images.githubusercontent.com/23335944/232018906-15b3606d-0291-40f0-9940-2689b837814e.png)

how is the `elements/passphrase.htm shows a toast when unlocking some other key` test related to this group?

**Comment by rrrooommmaaa** [comment]
Also, 2 tests were run with the same name -- `settings - error modal when page parameter invalid`? Is this possible?
