### ISSUE TITLE
use shared-tenant-fes for reporting errors

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5104]
`doSendErrorToFlowCryptComBackend` should be renamed to `doSendErrorToSharedTenantFes`

`https://flowcrypt.com/api/help/error` should be replaced with `https://flowcrypt.com/shared-tenant-fes/api/v1/log-collector/exception`

The new API has the following expected JSON input format:

```
    val name: String, // Exception name
    val message: String, // Exception message
    val url: String, // Error url
    val line: Long, // Error line
    val col: Long, // Error line col
    val line: Int, // Error line
    val col: Int, // Error line col
    val trace: String, // Stack trace text
    val version: String, // flowcrypt version
    val environment: String, // prod/dev/unknown
    val product: String, // web-ext/android/ios/web/web-portal
    val buildType: String, // consumer/enterprise
```

The API will be live with FES release 2023-07 later this month.

**Comment by ioanmo226** [comment]
How about `api/help/feedback` endpoint?
Has this endpoint migrated to `shared-tenant-fes` too?

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/blob/481f25d5c58bf46af657a96f1f37f0d4f30fa9ab/extension/js/common/api/flowcrypt-website.ts#L28

**Comment by tomholub** [comment]
Yes, that one is available at `https://flowcrypt.com/shared-tenant-fes/account/feedback` but there seems to be a bug - it requires authentication, whereas I meant that authentication to be optional. I'll take a look.

**Comment by tomholub** [comment]
I updated the above comment, the other endpoint functions fine, and you may start using it too as a replacement for the old api endpoint.

**Comment by tomholub** [comment]
Further, I updated the path to include `api/v1` in it, previously missing.

**Comment by ioanmo226** [comment]
```sh
curl 'https://flowcrypt.com/shared-tenant-fes/api/v1/log-collector/exception' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: en-US,en;q=0.9,de;q=0.8,ko;q=0.7,zh-CN;q=0.6,zh;q=0.5' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Origin: chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: none' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"name":"Error","message":"intentional error for debugging","url":"chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/chrome/settings/modules/experimental.htm?placeme","line":174,"col":15,"trace":"Error: intentional error for debugging\n    at Catch.test (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/platform/catch.js:174:15)\n    at ExperimentalView.<anonymous> (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/chrome/settings/modules/experimental.js:38:23)\n    at HTMLAnchorElement.uiEventHandle (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/browser/ui.js:68:48)\n    at HTMLAnchorElement.dispatch (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/lib/jquery.min.js:2:43184)\n    at y.handle (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/lib/jquery.min.js:2:41168)\n\n### Catch.reportErr calling stack ###\n#     at Catch.formatExceptionForReport (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/platform/catch.js:272:90)\n#     at Catch.onErrorInternalHandler (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/platform/catch.js:80:29)\n#     at Catch.reportErr (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/platform/catch.js:96:18)\n#     at Object._dispatchErr (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/browser/ui.js:91:19)\n#     at HTMLAnchorElement.uiEventHandle (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/js/common/browser/ui.js:76:26)\n#     at HTMLAnchorElement.dispatch (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/lib/jquery.min.js:2:43184)\n#     at y.handle (chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/lib/jquery.min.js:2:41168)\n# \n# url: chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi/chrome/settings/modules/experimental.htm?placement=settings&parentTabId=1623894173%3A0&acctEmail=[SCRUBBED]\n# \n######################\n","version":"8.4.6","environment":"chrome:ex:fork"}' \
  --compressed
```

**Comment by tomholub** [comment]
Yes, that one does require it, unlike previous endpoint.

That would mean, if the user is not logged in, we won't actually report it. In that case, you could `log.error` to say that user is not logged in and therefore not reporting.

**Comment by ioanmo226** [comment]
OK

**Comment by ioanmo226** [comment]
I'm having trouble passing the idToken to the `/account/feedback` endpoint. I'm currently using `Authorization: Bearer {idToken}` but I keep getting a 401 error.

Additionally, in the `Catch` class, it's difficult to obtain the `idToken` because we don't know which email to use to retrieve it. It's possible that an infrastructure change may be necessary. I'm currently investigating though.

https://github.com/FlowCrypt/flowcrypt-browser/blob/481f25d5c58bf46af657a96f1f37f0d4f30fa9ab/extension/js/common/platform/catch.ts#L301

**Comment by ioanmo226** [comment]
Here's curl request.

```sh
curl 'https://flowcrypt.com/shared-tenant-fes/api/v1/help/feedback' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: en-US,en;q=0.9,ko;q=0.8' \
  -H 'Authorization: Bearer {idToken}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Origin: chrome-extension://ihdcolfjbofmkpbgdjllobhhfmphaldn' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: none' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"email":"ioan@flowcrypt.com","message":"Test\n\n\nFlowCrypt chrome 8.4.6"}' \
  --compressed
```

**Comment by tomholub** [comment]
request looks ok, provided that the idToken including curly braces gets replaced. Except path is supposed to be `account/feedback` not `help/feedback`

**Comment by ioanmo226** [comment]
Ohh. yep.. sorry. i used `help/feedback` instead of `account/feedback`.
Btw I'm now getting `Domain disabled` error (FYI I'm currently trying with Flowcrypt enterprise account)

![image](https://user-images.githubusercontent.com/77344191/236230247-fd34c74f-09bb-447a-b048-512f591313c7.png)

**Comment by tomholub** [comment]
Only for some. On FlowCrypt.com it is was disabled in error. I'll re-enable it tonight or tomorrow.

**Comment by ioanmo226** [comment]
ok

What do you mean?
> Please be sure that the received error displays clearly when that happens.

**Comment by ioanmo226** [comment]
You mean in this error modal, we should display correct error message text?
![image](https://user-images.githubusercontent.com/77344191/236233736-e52ef8b3-2ba8-47aa-880d-279c8ff951a9.png)

**Comment by tomholub** [comment]
That modal should also contain the received error text.

**Comment by ioanmo226** [comment]
`/log-collector/exception ` returns `value too long` error.
Seems like `log-collector/exception` only accepts 1024 length (varchar) for `trace` value.

Do I have to slice only 1024 length trace string or will you increase this limit? 

```json
{
    "code": 500,
    "message": "ERROR: value too long for type VARCHAR(1024)",
    "details": "org.postgresql.util.PSQLException: ERROR: value too long for type VARCHAR(1024)\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)\n\tat org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)\n\tat com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\n\tat com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\n\tat org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)\n\tat org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:436)\n\tat org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1024)\n\tat org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)\n\tat org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)\n\tat com.flowcrypt.fes.store.DatabaseStore.upsertError(DatabaseStore.kt:398)\n\tat com.flowcrypt.fes.server.handlers.api.logcollector.LogCollectorExceptionPostKt$logCollectorExceptionPost$1.invoke(LogCollectorExceptionPost.kt:45)\n\tat com.flowcrypt.fes.server.handlers.api.logcollector.LogCollectorExceptionPostKt$logCollectorExceptionPost$1.invoke(LogCollectorExceptionPost.kt:44)\n\tat com.flowcrypt.fes.store.DatabaseStore.readWriteTransaction$lambda$0(DatabaseStore.kt:34)\n\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:531)\n\tat org.jooq.impl.Tools$3$1.block(Tools.java:6057)\n\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)\n\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)\n\tat org.jooq.impl.Tools$3.get(Tools.java:6054)\n\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)\n\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)\n\tat com.flowcrypt.fes.store.DatabaseStore.readWriteTransaction(DatabaseStore.kt:34)\n\tat com.flowcrypt.fes.server.handlers.api.logcollector.LogCollectorExceptionPostKt.logCollectorExceptionPost(LogCollectorExceptionPost.kt:44)\n\tat io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)\n\tat io.javalin.http.servlet.DefaultTasks.HTTP$lambda-8$lambda-6$lambda-5$lambda-4$lambda-3(DefaultTasks.kt:32)\n\tat io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)\n\tat io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)\n\tat io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)\n\tat io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)\n\tat jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)\n\tat io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:563)\n\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)\n\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)\n\tat org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)\n\tat org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"
}
```
