### ISSUE TITLE
when reporting errors, do not send any url parameters in url field

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5282]
For example: `url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_KHukGj`

Anything after `?` should be left out. Due to the variability inside the URL, the errors are not recognized as the same error, so there is a new record with count=1 for each of these errors on the backend, when it should have been a single record with count=many.

**Comment by martgil** [comment]
@tomholub Is my understanding correct that it refers to line 11 in the example below? If so, could the error be completely removed from all the query strings?

```
1 --------- BUG REPORT ----------
2 
3 [name]
4 composer: send: bad request (errMsg: Precondition check failed.)
5 
6 [stack]
7    at BrowserExtension.prepareBugReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/browser-extension.js:8:44)
8    at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:115:61)
9    at async ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:113:25)
10 
11 url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_QaBMVGNjox&acctEmail=[SCRUBBED]&parentTabId=1880404640%3A0
12 
13 
14 [error]
15 {
16   "status": 400,
17  "url": "https://www.googleapis.com/upload/gmail/v1/users/me/messages/send?uploadType=multipart",
18   "responseText": "{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Precondition check failed.\",\n    \"errors\": [\n      {\n        \"message\": \"Precondition check failed.\",\n        \"domain\": \"global\",\n        \"reason\": \"failedPrecondition\"\n      }\n    ],\n    \"status\": \"FAILED_PRECONDITION\"\n  }\n}\n",
19   "statusText": "error",
20   "resMsg": "Precondition check failed."
21 }
22 
23 [details]
24 {}
```

**Comment by tomholub** [comment]
yes, but especially the standalone url field sent in api request
