### ISSUE TITLE
Cannot read properties of undefined (reading 'replace') 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5295]
> title: TypeError                                         message: Cannot read properties of undefined (reading 'replace')                                         url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_tru                                         line: 213                                         column: 40                                         environment: chrome:ex:prod                                         build type: consumer

```
TypeError: Cannot read properties of undefined (reading 'replace')
at Buf.fromBase64UrlStr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/buf.js:213:40)
at ComposeQuoteModule.getAndDecryptMessage (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:88:59)
at async ComposeQuoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:43:56)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-render-module.js:97:29

### Catch.reportErr calling stack ###
# at Catch.formatExceptionForReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:273:90)
# at Catch.onErrorInternalHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:81:29)
# at Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:97:18)
# at ComposeQuoteModule.getAndDecryptMessage (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:173:31)
# at async ComposeQuoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:43:56)
# at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-render-module.js:97:29
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_true___&frameId=frame_fEzlJcPTER&skipClickPrompt=___cu_true___&ignoreDraft=___cu_false___&replyMsgId=%23msg-a%3Ar-764059238457043807&acctEmail=[SCRUBBED]&parentTabId=227631385%3A0
#
######################
```

**Comment by martgil** [comment]
@tomholub do you have any idea how I could replicate the following error above?

**Comment by tomholub** [comment]
A lot of times, it won't be possible to replicate. You'll have to use some intuition as to why it could possibly happen, and/or how to work around it or address it.

**Comment by tomholub** [comment]
Not just intuition, I mean there is an undefined where we didn't expect it, so the first step would be to either figure out how it may have gotten there, or update the types so that we know to expect it.

**Comment by martgil** [comment]
Thanks for the help - I'll figure it out.
