### ISSUE TITLE
Unable to send attachment when filename contains emoji

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5310]
When trying to send file with emoji in the filename I get error `Failed to send message due to: URIError: malformed URI sequence`:

```
malformed URI sequence
continuationEncodeChr@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-codec.js:661:28
continuationEncode@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-codec.js:712:31
MimeNode.prototype._buildHeaderValue/<@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:552:27
MimeNode.prototype._buildHeaderValue@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:549:46
MimeNode.prototype.build/<@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:382:34
MimeNode.prototype.build@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:371:23
MimeNode.prototype.build/<@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:471:33
MimeNode.prototype.build@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/lib/emailjs/emailjs-mime-builder.js:469:30
Mime.encode@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/js/common/core/mime.js:245:25
SendableMsg/this.toMime@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/js/common/api/email-provider/sendable-msg.js:49:39
Gmail/this.msgSend@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/js/common/api/email-provider/gmail/gmail.js:122:51
ComposeSendBtnModule/this.attemptSendMsg@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/chrome/elements/compose-modules/compose-send-btn-module.js:219:58
ComposeSendBtnModule/this.doSendMsgs@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/chrome/elements/compose-modules/compose-send-btn-module.js:269:55
ComposeSendBtnModule/this.extractProcessSendMsg@moz-extension://98c7ae9f-e7d0-484e-b0ae-722ed95db7b9/chrome/elements/compose-modules/compose-send-btn-module.js:91:47

    at <async> encode (/extension/js/common/core/mime.ts:239:25)
    at <async> toMime (/extension/js/common/api/email-provider/sendable-msg.ts:190:18)
    at <async> msgSend (/extension/js/common/api/email-provider/gmail/gmail.ts:90:19)
    at <async> attemptSendMsg (/extension/chrome/elements/compose-modules/compose-send-btn-module.ts:221:27)
```

**Comment by tomholub** [comment]
I think it would be acceptable to strip out the emoji? If that is a simplest way to fix it.

**Comment by sosnovsky** [comment]
Probably it shouldn't be too difficult to convert emojis to utf-8 string, and then it should work well for attachments and contact names. I think we should try it first, as users will expect emojis to persist when sending attachments, and if it needs complicated logic then just strip emojis.

**Comment by tomholub** [comment]
ok

**Comment by sosnovsky** [comment]
I was able to send attachment with emoji in filename after updating [emailjs-mime-codec.js](https://github.com/FlowCrypt/flowcrypt-browser/blob/8daed5fbe9008d246b0301b4f7952137eef1777e/extension/lib/emailjs/emailjs-mime-codec.js) to use code from the latest https://github.com/emailjs/emailjs-mime-codec/tree/master.
So probably updating `emailjs` files will make it possible to support emoji symbols (and other utf-8 symbols too)

**Comment by tomholub** [comment]
Yeah, but I've made various fixes in the library without upstreaming them. So it may be a messy process. Hopefully we have tests for that. But right now, I recommend to just bring the patch here and file updating the library for another issue.
