### ISSUE TITLE
[Needs help] Moving a typescript file to other directory + updated import paths leads to Class as not defined

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5335]
Description: I'm working with #5316 and having some trouble after updating the google-auth.ts and create oauth.ts file. The old pr that I published is https://github.com/FlowCrypt/flowcrypt-browser/pull/5326 - it complains about GoogleAuth being not defined.

I have done several debugging and I'm clueless why is that. So I had created a fresh PR https://github.com/FlowCrypt/flowcrypt-browser/pull/5334 with changes to just move the google-auth.ts to  common/api/authentication but the error about GoogleAuth being undefined that occurs in `Google.gmailCall()` even though the import paths where correctly updated.

Stack trace:

```
webmail_bundle.js:70 ReferenceError: GoogleAuth is not defined
    at Google.gmailCall (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8911:48)
    at Gmail.msgGet (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8482:37)
    at Downloader.msgGetFull (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:10989:46)
    at chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11665:75
    at MessageRenderer.msgGetProcessed (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11670:23)
    at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13826:79)
    at GmailElementReplacer.everything (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13801:18)
    at Object.handler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13735:55)
    at Object.start (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15238:46)
    at async entrypoint (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15060:21)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:18:28)
    at <async> msgGet (/extension/js/common/api/email-provider/gmail/gmail.ts:110:18)
    at <async> msgGetFull (/extension/js/common/downloader.ts:53:22)
    at <async> <anonymous> (/extension/js/common/message-renderer.ts:391:20)

### Catch.reportErr calling stack ###
#     at Catch.formatExceptionForReport (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:279:90)
#     at Catch.onErrorInternalHandler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:87:29)
#     at Catch.reportErr (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:103:18)
#     at GmailElementReplacer.handleException (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:14274:27)
#     at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13829:30)
# 
# url: https://gmail.localhost:43199/gmail/1866867cfdb8b61e
# 
######################

Catch.onErrorInternalHandler @ webmail_bundle.js:70
Catch.reportErr @ webmail_bundle.js:103
GmailElementReplacer.handleException @ webmail_bundle.js:14274
GmailElementReplacer.replaceArmoredBlocks @ webmail_bundle.js:13829
Show 4 more frames
Show less
webmail_bundle.js:74 GoogleAuth is not defined
ReferenceError: GoogleAuth is not defined
    at Google.gmailCall (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8911:48)
    at Gmail.msgGet (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8482:37)
    at Downloader.msgGetFull (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:10989:46)
    at chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11665:75
    at MessageRenderer.msgGetProcessed (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11670:23)
    at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13826:79)
    at GmailElementReplacer.everything (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13801:18)
    at Object.handler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13735:55)
    at Object.start (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15238:46)
    at async entrypoint (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15060:21)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:18:28)
    at <async> msgGet (/extension/js/common/api/email-provider/gmail/gmail.ts:110:18)
    at <async> msgGetFull (/extension/js/common/downloader.ts:53:22)
    at <async> <anonymous> (/extension/js/common/message-renderer.ts:391:20)
```
Any suggestion or feedback is highly appreciated. Thanks in advance.

**Comment by martgil** [comment]
@sosnovsky greetings, may I ask for some assistance here. Thank you!

**Comment by sosnovsky** [comment]
@martgil I checked built `webmail_bundle.js` and it didn't contain `class GoogleAuth`, so for some reason it wasn't included in the final build. But then I found that we have `bundle-content-scripts.ts` which lists all files added to the build, and after adding new directory error has gone.

Solution: add 
```ts
getFilesInDir(`${sourceDir}/js/common/api/authentication`, /\.js$/, false),
```
at https://github.com/FlowCrypt/flowcrypt-browser/blob/issue-5316-create-new-oauth-class-v2/tooling/bundle-content-scripts.ts#L47

**Comment by martgil** [comment]
Thank you so much. I understand the building process a bit better now. I also knew that the dir that is supplied in `getFilesInDir` is in alphabetical order so the reference to the OAuth class will be undefined because the google-auth.js file will be written first before the oauth.js. I've tried renaming the file to auth-oauth.ts so that it will be written in the `webmail_bundle.js` first before google-auth.ts when they've been compiled but I think it will be confusing if the OAuth class is used in other places. 

I am thinking of having `getFilesInDir()` another argument boolean argument called 'reverseFilesInDir' for reversing the order of filesInDir in `getFilesInDir()` so that oauth.ts will be written first without having a complex file re-ordering process within the `getFilesInDir()` or `buildContentScript()`.

**Comment by sosnovsky** [comment]
> Should the wiki be updated with this, in case it's not there?

We have information about building content script files at https://github.com/FlowCrypt/flowcrypt-browser/wiki/FlowCrypt-Project-Structure-and-Overview#content-scripts
