### ISSUE TITLE
Canceling passphrase dialog sometimes leads to glitches

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#5373]
I rarely see an unexpected decryption error like this
```
----- mockBackendData Catch.reportErr -----21:30
name: OperationError21:30
message: 21:30
url: https://gmail.localhost:33675/gmail/17daefa0eb077da621:30
trace: Error21:30
    at <async> decrypt (/extension/js/common/symmetric-message-encryption.ts:42:26)21:30
    at <async> <anonymous> (/extension/js/common/browser/browser-msg.ts:349:17)21:30
### Catch.reportErr calling stack ###21:30
#     at Catch.formatExceptionForReport (chrome-extension://kimlbdocogdofnhjfioniflhebimmknh/js/content_scripts/webmail_bundle.js:279:90)21:30
#     at Catch.onErrorInternalHandler (chrome-extension://kimlbdocogdofnhjfioniflhebimmknh/js/content_scripts/webmail_bundle.js:87:29)21:30
#     at Catch.reportErr (chrome-extension://kimlbdocogdofnhjfioniflhebimmknh/js/content_scripts/webmail_bundle.js:103:18)21:30
# 21:30
# url: https://gmail.localhost:33675/gmail/17daefa0eb077da621:30
# 21:30
######################
```
It may be somehow connected with `PassphraseView.closeDialog` sending two messages at once.

**Comment by sosnovsky** [comment]
Seems to be not reproducible in the latest builds.
