### ISSUE TITLE
"Cannot read properties of undefined (reading 'commonAncestorContainer')" error when opening encrypted thread

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5467]
After upgrading squire-rte to v2 such error appears when opening any encrypted thread:

```
TypeError: Cannot read properties of undefined (reading 'commonAncestorContainer')
    at Ce.<anonymous> (compose-input-module.js:211:53)
    at Ce.fireEvent (squire.js:4:1845)
    at Ce._updatePath (squire.js:4:5207)
    at Ce.setHTML (squire.js:4:8677)
    at ComposeInputModule.initSquire (compose-input-module.js:86:29)
    at ComposeInputModule.setHandlers (compose-input-module.js:14:18)
    at ComposeView.setHandlers (compose.js:202:30)
    at view.js:29:52
```

**Comment by sosnovsky** [comment]
fixed in https://github.com/FlowCrypt/flowcrypt-browser/pull/5507
