### ISSUE TITLE
"Failed to execute 'json' on 'Response'" error in console on message send

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5886]
I noticed such error in console which sometimes occurs when sending encrypted message:

```
Failed to execute 'json' on 'Response': Unexpected end of JSON input

SyntaxError: Unexpected end of JSON input
at Api.ajax (chrome-extension://EXTENSION_ID/js/common/api/shared/api.js:223:73)
at async performAjaxRequest (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/authentication/google/google-oauth.js:93:33)
at async GoogleOAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/authentication/google/google-oauth.js:101:24)
at async Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/google.js:38:20)
at async Gmail.draftDelete (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/email-provider/gmail/gmail.js:90:20)
at async ComposeDraftModule.draftDelete (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-draft-module.js:109:25)
at async Promise.all (index 0)
at async ComposeSendBtnModule.doSendMsgs (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:292:17)
at async ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:95:32)
at <async> ajax (/extension/js/common/api/shared/api.ts:98:4)
at <async> performAjaxRequest (/extension/js/common/api/authentication/google/google-oauth.ts:88:31)
at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/authentication/google/google-oauth.ts:85:4)
at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:19:28)
at <async> draftDelete (/extension/js/common/api/email-provider/gmail/gmail.ts:81:23)
```

**Comment by sosnovsky** [comment]
Hi @ioanmo226, can you please work on this one after finishing https://github.com/FlowCrypt/flowcrypt-browser/pull/5887, thanks!

**Comment by ioanmo226** [comment]
Okay

**Comment by ioanmo226** [comment]
Hmm... Can't reproduce issue. Digging more now

**Comment by ioanmo226** [comment]
@sosnovsky Could you tell me how often this error occurs?
Also if possible could you share reproduce steps?

**Comment by ioanmo226** [comment]
Ohhh, Yep.
I thought original error was sending failed because of that error.
I tried to send message and it was succeed so I didn't check console.

Now I noticed that current issue is not message send failure but console.log error.
Sorry for confusion.

**Comment by ioanmo226** [comment]
Ohhh, Yep.
I thought original error was sending failed because of that error.
I tried to send message and it was succeed so I didn't check console.

Now I noticed that current issue is not message send failure but console.log error.
Sorry for confusion.

**Comment by sosnovsky** [comment]
Oh, I should mentioned in description that sending works well, it's notable only in console, so it's not so critical as failing message sending.
