### ISSUE TITLE
Error: Failed to execute 'btoa' on 'Window'

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#728]
```
Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at str_base64url_encode (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:351:12)
    at Object.str_html_attribute_encode [as html_attribute_encode] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:340:12)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/shared/compose.js:555:134
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3146:11
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1961:13
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:3477:16
    at Object.success (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/common.js:1963:11)
    at i (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:2:27914)
    at z (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/jquery.min.js:4:12120)
```

**Comment by tomholub** [comment]
We don't rely on this anymore
